### ISSUE TITLE
SDK errors with 1.9.62

### ISSUE THREAD

**Issue by igniteflow** [potatolondon/djangae#1003]
Hitting an import error when running runserver

```
$ ./manage.py runserver
Traceback (most recent call last):
  File "./manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ptysoe/Projects/potato/djangae/testapp/djangae/core/management/__init__.py", line 39, in execute_from_command_line
    return _execute_from_command_line(djangae_namespace.sandbox, argv, parser=djangae_parser, **overrides)
  File "/home/ptysoe/Projects/potato/djangae/testapp/djangae/core/management/__init__.py", line 60, in _execute_from_command_line
    **sandbox_overrides
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/ptysoe/Projects/potato/djangae/testapp/djangae/sandbox.py", line 551, in activate
    with SANDBOXES[sandbox_name](**kwargs):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/ptysoe/Projects/potato/djangae/testapp/djangae/sandbox.py", line 210, in _local
    devappserver2._setup_environ(configuration.app_id)
AttributeError: 'module' object has no attribute '_setup_environ'
```

* Djangae version: `63e30467b4612e73b9c2d1503cb672517f240f28`
* Django version: 1.8.19alpha
* App Engine SDK version: 1.9.62
* Using Cloud SDK: no

**Comment by interpegasus** [comment]
It seems to work fine via:
1. Delete current app engine
`$ rm -rf /sitepackages/dev/google_appengine`
2. Download latest version of app engine:
`$ python2 ./install_deps`
3. Run the server
`$ python2 ./manage.py runserver`

**Python Version**
$ python2 --version
Python 2.7.14

**Comment by jturmel** [comment]
I think the real issue here is that `_setup_environ` got moved to `utils.setup_environ` and then beyond that `cleanup_stubs` got moved to `stub_utils.cleanup_stubs`

**Comment by davidwtbuxton** [comment]
Related #1035

**Comment by davidwtbuxton** [comment]
Closing, discussion moved to #1035.
