### ISSUE TITLE
`Illegal string "dev~None" in dataset id.` when application line is not in app.yaml

### ISSUE THREAD

**Issue by nealedj** [potatolondon/djangae#1008]
Issue description
The gcloud app deployment commands require there to not be an `application:` line in the app.yaml file. However, if this is removed then the datastore stub appears to throw an error when the application is run using `runserver`.

If the application is run via dev_appserver.py directly then this issue does not occur.

Steps to reproduce
- Remove `application:` line from app.yaml
- Run application (`./manage.py runserver`)
- Make a request that will cause a datastore operation

Traceback or other info
```
Traceback (most recent call last):
  File "./third_party/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "./third_party/django/core/handlers/base.py", line 244, in _legacy_get_response
    response = middleware_method(request)
  File "./common/authentication/middleware.py", line 101, in process_request
    return super(AuthenticationMiddleware, self).process_request(request)
  File "./third_party/djangae/contrib/gauth/middleware.py", line 39, in process_request
    login(request, django_user)
  File "./third_party/django/contrib/auth/__init__.py", line 135, in login
    request.session.cycle_key()
  File "./third_party/django/contrib/sessions/backends/base.py", line 314, in cycle_key
    self.create()
  File "./third_party/django/contrib/sessions/backends/db.py", line 54, in create
    self.save(must_create=True)
  File "./third_party/django/contrib/sessions/backends/db.py", line 87, in save
    obj.save(force_insert=must_create, force_update=not must_create, using=using)
  File "./third_party/django/db/models/base.py", line 806, in save
    force_update=force_update, update_fields=update_fields)
  File "./third_party/django/db/models/base.py", line 836, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "./third_party/django/db/models/base.py", line 922, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "./third_party/django/db/models/base.py", line 961, in _do_insert
    using=using, raw=raw)
  File "./third_party/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "./third_party/django/db/models/query.py", line 1060, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "./third_party/django/db/models/sql/compiler.py", line 1099, in execute_sql
    cursor.execute(sql, params)
  File "./third_party/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "./third_party/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "./third_party/djangae/db/backends/appengine/base.py", line 88, in execute
    self.returned_ids = sql.execute()
  File "./third_party/djangae/db/backends/appengine/commands.py", line 769, in execute
    return insert_chunk(self.included_keys, self.entities)
  File "./third_party/djangae/db/backends/appengine/commands.py", line 747, in insert_chunk
    return txn()
  File "./third_party/google_appengine/google/appengine/api/datastore.py", line 2732, in inner_wrapper
    return RunInTransactionOptions(options, func, *args, **kwds)
  File "./third_party/google_appengine/google/appengine/api/datastore.py", line 2630, in RunInTransactionOptions
    ok, result = _DoOneTry(function, args, kwargs)
  File "./third_party/google_appengine/google/appengine/api/datastore.py", line 2650, in _DoOneTry
    result = function(*args, **kwargs)
  File "./third_party/djangae/db/backends/appengine/commands.py", line 729, in txn
    reserve_id(key.kind(), key.id_or_name(), self.namespace)
  File "./third_party/google_appengine/google/appengine/api/datastore.py", line 2770, in inner_wrapper
    return func(*args, **kwds)
  File "./third_party/djangae/db/backends/appengine/commands.py", line 618, in reserve_id
    _GetConnection()._reserve_keys([key])
  File "./third_party/google_appengine/google/appengine/datastore/datastore_rpc.py", line 2172, in _reserve_keys
    self._async_reserve_keys(None, keys).get_result()
  File "./third_party/google_appengine/google/appengine/datastore/datastore_rpc.py", line 923, in get_result
    results = self.__rpcs[0].get_result()
  File "./third_party/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "./third_party/google_appengine/google/appengine/datastore/datastore_rpc.py", line 2215, in __reserve_keys_hook
    self.check_rpc_success(rpc)
  File "./third_party/google_appengine/google/appengine/datastore/datastore_rpc.py", line 1373, in check_rpc_success
    raise _ToDatastoreError(err)
BadRequestError: Illegal string "dev~None" in dataset id.
```

* Djangae version: 0.9.10
* Django version: 1.11
* App Engine SDK version: 1.9.24
* Using Cloud SDK: yes

**Comment by rspier** [comment]
I think the problem is the "N" in None.  (All of the regular expressions are case sensitive.)

_DATASET_ID_PARTITION_STRING = (r'[a-z\d\-]{1,%d}'
                                % datastore_pbs.MAX_DATASET_ID_SECTION_LENGTH)
_DATASET_ID_DOMAIN_STRING = (
    r'[a-z\d][a-z\d\-\.]{0,%d}'
    % (datastore_pbs.MAX_DATASET_ID_SECTION_LENGTH - 1))
_DATASET_ID_DISPLAY_STRING = (
    r'[a-z\d][a-z\d\-]{0,%d}'
    % (datastore_pbs.MAX_DATASET_ID_SECTION_LENGTH - 1))
_DATASET_ID_STRING = ('(?:(?:%s)~)?(?:(?:%s):)?(?:%s)'
                      % (_DATASET_ID_PARTITION_STRING,
                         _DATASET_ID_DOMAIN_STRING,
                         _DATASET_ID_DISPLAY_STRING))
_DATASET_ID_RE = re.compile('^%s$' % _DATASET_ID_STRING)

**Comment by rspier** [comment]
Also, workaround might be to pass `--app_id` on manage.py command line.

```
$ ./manage.py runserver --help
usage: manage.py [-h] [--sandbox {test,remote,local}] [--app_id APP_ID]

optional arguments:
  -h, --help            show this help message and exit
  --sandbox {test,remote,local}
  --app_id APP_ID       GAE APPLICATION ID
```

**Comment by seawolf42** [comment]
I am unable to reproduce this using newer SDK versions:

```bash
$ gcloud --version
Google Cloud SDK 170.0.0
app-engine-python 1.9.57
beta 2017.03.24
bq 2.0.25
core 2017.09.01
gsutil 4.27
kubectl 
Updates are available for some Cloud SDK components.  To install them,
please run:
  $ gcloud components update
$ python manage.py runserver
INFO     2017-12-18 04:54:22,330 blobstore_service.py:74] Starting blobstore service on localhost:8012
Validating models...

System check identified no issues (0 silenced).
December 18, 2017 - 14:54:22
Django version 1.11.8, using settings 'settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

INFO     2017-12-18 14:54:22,900 devappserver2.py:116] Skipping SDK update check.
INFO     2017-12-18 14:54:22,906 api_server.py:313] Starting API server at: http://127.0.0.1:8010
INFO     2017-12-18 14:54:22,910 dispatcher.py:226] Starting module "default" running at: http://localhost:8000
INFO     2017-12-18 14:54:22,911 admin_server.py:116] Starting admin server at: http://127.0.0.1:8011
WARNING  2017-12-18 14:54:30,389 middleware.py:131] settings.CSRF_COOKIE_SECURE is not set to True, this is insecure
WARNING  2017-12-18 14:54:30,389 middleware.py:131] settings.SESSION_COOKIE_SECURE is not set to True, this is insecure
INFO     2017-12-18 14:54:30,433 runserver.py:367] default: "GET /admin HTTP/1.1" 301 -
INFO     2017-12-18 14:54:31,037 runserver.py:367] default: "GET /admin/ HTTP/1.1" 200 2291
INFO     2017-12-18 14:54:31,068 runserver.py:367] default: "GET /static/admin/css/dashboard.css HTTP/1.1" 304 -
INFO     2017-12-18 14:54:31,068 runserver.py:367] default: "GET /static/admin/css/base.css HTTP/1.1" 304 -
INFO     2017-12-18 14:54:31,122 runserver.py:367] default: "GET /static/admin/css/fonts.css HTTP/1.1" 304 -
INFO     2017-12-18 14:54:31,159 runserver.py:367] default: "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 -
INFO     2017-12-18 14:54:31,160 runserver.py:367] default: "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 -
INFO     2017-12-18 14:54:31,160 runserver.py:367] default: "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 -
INFO     2017-12-18 14:54:31,161 runserver.py:367] default: "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 -
INFO     2017-12-18 14:54:31,180 runserver.py:367] default: "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 -
INFO     2017-12-18 14:54:31,411 runserver.py:367] default: "GET /favicon.ico HTTP/1.1" 200 350
^CINFO     2017-12-18 14:54:40,685 api_server.py:945] Applying all pending transactions and saving the datastore
INFO     2017-12-18 14:54:40,736 api_server.py:948] Saving search indexes
INFO     2017-12-18 14:54:53,312 api_server.py:945] Applying all pending transactions and saving the datastore
INFO     2017-12-18 14:54:53,312 api_server.py:948] Saving search indexes
$ more app.yaml
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /_ah/(mapreduce|queue|warmup).*
  script: wsgi.application
  secure: always
  login: admin

- url: /(admin).*
  script: wsgi.application
  secure: always
  login: admin

- url: /.*
  script: wsgi.application
  secure: always
```

**Comment by rspier** [comment]
Your test is not doing any datastore operations, AFAICT from the log.
