### ISSUE TITLE
Importing the devappserver sandbox module is not permitted

### ISSUE THREAD

**Issue by wittfabian** [potatolondon/djangae#1035]
Hitting an import error when running dev_appserver

```
File "C:\Users\Redheads\Documents\python\hvointern-webpage\lib\djangae\compat.py", line 4, in <module>
from google.appengine.tools.devappserver2.python.runtime import sandbox

...\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\devappserver2\python\runtime\sandbox.py", line 1106, in load_module 'import.'.format(fullname))

ImportError: Importing the devappserver sandbox module (google.appengine.tools.devappserver2.python.runtime.sandbox) from user application code is not permitted. Please remove this import.
```

- Djangae version: master@dc2725b
- Django version: 1.11

- Google Cloud SDK 190.0.1
- app-engine-python 1.9.67
- app-engine-python-extras 1.9.63
- bq 2.0.29
- core 2018.02.22
- gsutil 4.28

**Comment by davidwtbuxton** [comment]
Same. Server starts fine, then the error is raised on the first request.

```
$ dev_appserver.py . --storage_path=.storage
INFO     2018-02-27 16:55:32,570 api_server.py:265] Starting API server at: http://localhost:50053
INFO     2018-02-27 16:55:32,577 dispatcher.py:255] Starting module "default" running at: http://localhost:8080
INFO     2018-02-27 16:55:32,585 admin_server.py:152] Starting admin server at: http://localhost:8000
ERROR    2018-02-27 16:55:48,666 wsgi.py:263] 
Traceback (most recent call last):
  File "/usr/local/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/usr/local/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/usr/local/google_appengine/google/appengine/runtime/wsgi.py", line 96, in LoadObject
    __import__(cumulative_path)
  File "/Users/jeff/example/example/wsgi.py", line 7, in <module>
    from djangae.wsgi import DjangaeApplication
  File "/Users/jeff/example/libs/djangae/wsgi.py", line 16, in <module>
    fix_c_whitelist()
  File "/Users/jeff/example/libs/djangae/wsgi.py", line 5, in fix_c_whitelist
    from djangae.compat import sandbox
  File "/Users/jeff/example/libs/djangae/compat.py", line 4, in <module>
    from google.appengine.tools.devappserver2.python.runtime import sandbox
  File "/usr/local/google_appengine/google/appengine/tools/devappserver2/python/runtime/sandbox.py", line 1106, in load_module
    'import.'.format(fullname))
ImportError: Importing the devappserver sandbox module (google.appengine.tools.devappserver2.python.runtime.sandbox) from user application code is not permitted. Please remove this import.
```

Python 2.7.14
SDK 1.9.67
Djangae current head of master dc2725bde19f50e7dfa0438c72fbaa8bc4b48bb7

**Comment by wittfabian** [comment]
#1041 is this the fix?

**Comment by wittfabian** [comment]
Is there a solution?

**Comment by davidwtbuxton** [comment]
Notes:

- SDK 1.9.58 moved google.appengine.tools.devappserver2.python_runtime to google.appengine.tools.devappserver2.python.instance_factory
- SDK 1.9.61 moved google.appengine.tools.devappserver2.devappserver2:_setup_environ to google.appengine.tools.devappserver2.util:setup_environ
- SDK 1.9.65 added google.appengine.tools.devappserver2.python.runtime.sandbox:SandboxAccessPreventionImportHook which is responsible for this exception. Djangae imports the sandbox module in order to add _sqlite3 to the allowed C-based modules (it is not available in production).

**Comment by wittfabian** [comment]
@davidwtbuxton You saved my day!!

**Comment by philoozushi** [comment]
It would be nice to show friendly errors when Djangae doesn't work with the latest SDK yet.

Like storing the latest supported SDK version in a constant, comparing SDK version at startup, and if an exception raises, warn that this could be related with the SDK version.

**Comment by seawolf42** [comment]
I'd be happy to make that change, but I don't actually know what the latest supported version is. From the conversation above, it looks like it *might* be 1.9.57?

**Comment by seawolf42** [comment]
So I can get my project running using djangae versions 0.9.10, 0.9.11, and 20aedb with gcloud version 170.0.0, but nothing newer... this correlates to app-engine-python 1.9.57, and is just now a year old. I'll create a PR go identify newer versions and give a friendly error.

**Comment by 0xdc** [comment]
Are there any efforts (e.g. to provide a branch) to get this to work with more modern SDK versions?

**Comment by davidwtbuxton** [comment]
@0xdc No, but I agree this should be a priority. Last time I checked, it may involve disabling the sqlite support (which Djangae explicitly enables despite the SDK explicitly disabling it because it isn't available on App Engine).
