### ISSUE TITLE
AttributeError raised when running makemigrations command

### ISSUE THREAD

**Issue by maccinza** [potatolondon/djangae#1042]
Would you like assistance or advice?  Please using the [djangae mailing list](https://groups.google.com/forum/#!forum/djangae-users) ([djangae-users@googlegroups.com](mailto:djangae-users@googlegroups.com)) for questions and discussion.

Issue description

AttributeError is raised when running django commands.

Steps to reproduce

Run makemigrations command:
`python manage.py makemigrations`

Traceback or other info

`Traceback (most recent call last):
  File "/.../sitepackages/runtime/djangae/core/management/__init__.py", line 43, in execute_from_command_line
    return _execute_from_command_line(djangae_namespace.sandbox, argv, parser=djangae_parser, **overrides)
  File "/.../sitepackages/runtime/djangae/core/management/__init__.py", line 75, in _execute_from_command_line
    raise
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/.../sitepackages/runtime/djangae/sandbox.py", line 559, in activate
    yield
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/.../sitepackages/runtime/djangae/sandbox.py", line 274, in _local
    api_server.cleanup_stubs()
AttributeError: 'module' object has no attribute 'cleanup_stubs'`

The fix is quite simple, the proper call should be:
`api_server.stub_util.cleanup_stubs()`

* Djangae version: 0.9.11-alpha
* Django version: 1.11.5
* App Engine SDK version: 1.9.67
* Using Cloud SDK: Yes

**Comment by davidwtbuxton** [comment]
Related to #1035
