### ISSUE TITLE
ListCreateAPIView throws IndexError: list index out of range error

### ISSUE THREAD

**Issue by vinaymavi** [potatolondon/djangae#1043]
Would you like assistance or advice?  Please using the [djangae mailing list](https://groups.google.com/forum/#!forum/djangae-users) ([djangae-users@googlegroups.com](mailto:djangae-users@googlegroups.com)) for questions and discussion.

Issue description
rest_framework generic view ListCreateAPIView throws **IndexError: list index out of range error** on AppEngine deployed version. 
Steps to reproduce
create an api with generic view ListCreateAPIView and deploy this to AppEngine.
Traceback or other info
```
Internal Server Error: /admin/ (/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/core/handlers/exception.py:124)
Traceback (most recent call last):
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/response.py", line 86, in rendered_content
    content = template.render(context, self._request)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/base.py", line 208, in render
    return self._render(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/defaulttags.py", line 323, in render
    return nodelist.render(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/defaulttags.py", line 323, in render
    return nodelist.render(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/base.py", line 1044, in render
    output = self.filter_expression.resolve(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/base.py", line 711, in resolve
    obj = self.var.resolve(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/base.py", line 852, in resolve
    value = self._resolve_lookup(context)
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/template/base.py", line 915, in _resolve_lookup
    current = current()
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/contrib/admin/models.py", line 142, in get_admin_url
    if self.content_type and self.object_id:
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/django/db/models/fields/related_descriptors.py", line 179, in __get__
    rel_obj = qs.get()
  File "/base/data/home/apps/b~slidesprodv2/20180303t215521.408047226860619218/sitepackages/prod/djangae/contrib/contenttypes/models.py", line 20, in get
    return self[0]
IndexError: list index out of range
```
* Djangae version: x.x.x / master@commit 
   djangae==0.9.10
* Django version: x.x.x
django==1.10
* App Engine SDK version: 1.9.xx
release: "1.9.40"
* Using Cloud SDK: yes/no
  yes(using google cloud command line tool)

**Comment by vinaymavi** [comment]
issue got resolved after updating Django version 1.10 to 1.11.
