### ISSUE TITLE
fetching a model entity in remote shell when its read from memcache causes unpickle error

### ISSUE THREAD

**Issue by jacobg** [potatolondon/djangae#1085]
When using remote shell, I sometimes get this exception when fetching a queryset:
```
Traceback (most recent call last):
  File "src/sitepackages/prod/django/db/models/sql/compiler.py", line 889, in execute_sql
    cursor.execute(sql, params)
  File "src/sitepackages/prod/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "src/sitepackages/prod/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "src/sitepackages/prod/djangae/db/backends/appengine/base.py", line 81, in execute
    self.rowcount = self.last_select_command.execute() or -1
  File "src/sitepackages/prod/djangae/db/backends/appengine/commands.py", line 564, in execute
    self._fetch_results(self.gae_query)
  File "src/sitepackages/prod/djangae/db/backends/appengine/commands.py", line 538, in _fetch_results
    for entity in query.Run(limit=limit, offset=offset):
  File "src/sitepackages/prod/djangae/db/backends/appengine/meta_queries.py", line 442, in Run
    ret = caching.get_from_cache(self._identifier, self._namespace)
  File "src/sitepackages/prod/djangae/db/backends/appengine/caching.py", line 333, in get_from_cache
    ret = _get_entity_from_memcache(cache_key)
  File "src/sitepackages/prod/djangae/db/backends/appengine/caching.py", line 209, in _get_entity_from_memcache
    return get_memcache_client().get_multi([cache_key]).get(cache_key)
  File "src/sitepackages/prod/djangae/db/backends/appengine/caching.py", line 87, in get_multi
    key_mapping.keys(), key_prefix=key_prefix, namespace=namespace, for_cas=for_cas
  File "src/sitepackages/dev/google_appengine/google/appengine/api/memcache/__init__.py", line 590, in get_multi
    return rpc.get_result()
  File "src/sitepackages/dev/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "src/sitepackages/dev/google_appengine/google/appengine/api/memcache/__init__.py", line 630, in __get_hook
    returned_item.flags(), self._do_unpickle)
  File "src/sitepackages/dev/google_appengine/google/appengine/api/memcache/__init__.py", line 271, in _decode_value
    return do_unpickle(value)
  File "src/sitepackages/dev/google_appengine/google/appengine/api/memcache/__init__.py", line 402, in _do_unpickle
    return unpickler.load()
UnpicklingError: NEWOBJ class argument isn't a type object
```

If I set DJANGAE_CACHE_ENABLED=False, or if I delete the memcache entry for the model entity matching the query set, then there’s no error. As soon as memcache gets repopulated with that entity, then subsequent queries fail again.

One possible solution is to convert the entity to protobuf before sending to memcached for pickling. The following (very old!) article recommends that:
http://blog.notdot.net/2009/9/Efficient-model-memcaching
The article doesn't mention this error, but perhaps protobuf is more resilient to pickling errors than the entity class itself. It's easy to convert to/from protobuf using the Entity class methods ToPb and FromPb.

A couple other incidental issues I noticed:

I also noticed in `caching.add_entities_to_cache` a line of code I do not understand:
```
            for ent_identifiers, entity in zip(identifiers, entities):
                mc_key_entity_map.update({
                    identifier: entity for identifier in ent_identifiers
                })
```
Why do we do `identifier: entity for identifier in ent_identifiers`? Is it setting the same entity value multiple times for identifier?

It also seems that remote shell queries don’t add entities to the memcache; they just read them. Only my regular app code seems to do that? Is that expected?

**Comment by adamalton** [comment]
The pickling error is a bug in App Engine: https://issuetracker.google.com/issues/35893628  Feel free to star the issue and comment on it 😉 

You might find that #783 adds a bit of context.

Setting `DJANGAE_CACHE_ENABLED=False` is the workaround until GAE is fixed.

> Why do we do identifier: entity for identifier in ent_identifiers? Is it setting the same entity value multiple times for identifier?

Not quite, it's setting the same entity value for several different identifiers.  Supposing you have a model with a unique field (which is not the PK), it will cache the entity using both the PK value and the unique field value.  So then if you query for the entity by either of those fields it will be able to fetch it from the cache.

> It also seems that remote shell queries don’t add entities to the memcache; they just read them. Only my regular app code seems to do that? Is that expected?

Not sure.   But are you sure that that's what's happening?  You also said: "As soon as memcache gets repopulated with that entity, then subsequent queries fail again.", which suggests that the remote shell *is* adding the entities to memcache.  AFAIK the remote shell will be talking to your local memcache (on your computer in the SDK, rather than the actual App Engine memcache), so if it's being repopulated then surely it must be the remote shell that's populating it?

**Comment by jacobg** [comment]
Just for reference, this issue is still the same when using latest gcloud sdk. I imagine perhaps the new djangae v2 will use the newer datastore client, and that it won't have this issue.
