### ISSUE TITLE
Production error

### ISSUE THREAD

**Issue by jacobg** [potatolondon/djangae#1103]
The following commit is causing startup failure in GAE production:
potatolondon/djangae@36974d0

Exception:
```
2018-09-27 20:16:35.804 EDT
    from djangae import checks
2018-09-27 20:16:35.804 EDT
  File "/base/data/home/apps/s~/1.412878905325365371/sitepackages/prod/djangae/checks.py", line 8, in <module>
2018-09-27 20:16:35.804 EDT
    from google.appengine.tools.sdk_update_checker import GetVersionObject, _VersionList
2018-09-27 20:16:35.804 EDT
ImportError: No module named sdk_update_checker
```

Looks like sdk_update_checker only exists in local dev sdk, not in production. And so the check should only be made locally, not in production.

Perhaps this is the fix in djangae/checks.py:
```
try:
    from google.appengine.tools.sdk_update_checker import GetVersionObject, _VersionList
except ImportError as e:
    GetVersionObject = None
```
```
@register
def check_app_engine_sdk_version(app_configs=None, **kwargs):
    errors = []
    if GetVersionObject:
        sdk_version = tuple(_VersionList(GetVersionObject()['release']))
        if sdk_version > MAX_APP_ENGINE_SDK_VERSION:
                errors.append(Warning(
                    "MAX_APP_ENGINE_SDK_VERSION",
                    hint="You are using a version of the App Engine SDK that is not yet supported",
                    id='djangae.W002',
                ))
    return errors
```

Do you agree this fix needs to be made?

**Comment by davidwtbuxton** [comment]
Full traceback on app startup:

```

Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/ec315266546cb44c/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/ec315266546cb44c/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/ec315266546cb44c/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 96, in LoadObject
    __import__(cumulative_path)
  File "/base/data/home/apps/e~foo/dbux.413009471273764141/project/wsgi.py", line 13, in <module>
    application = DjangaeApplication(get_wsgi_application())
  File "/base/data/home/apps/e~foo/dbux.413009471273764141/libs/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/base/data/home/apps/e~foo/dbux.413009471273764141/libs/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/base/data/home/apps/e~foo/dbux.413009471273764141/libs/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/base/data/home/apps/e~foo/dbux.413009471273764141/libs/djangae/apps.py", line 23, in ready
    self._check_content_types()
  File "/base/data/home/apps/e~foo/dbux.413009471273764141/libs/djangae/apps.py", line 56, in _check_content_types
    from djangae import checks
  File "/base/data/home/apps/e~foo/dbux.413009471273764141/libs/djangae/checks.py", line 8, in <module>
    from google.appengine.tools.sdk_update_checker import GetVersionObject, _VersionList
ImportError: No module named sdk_update_checker
```

Djangae version commit e69afd0ff3c1208bd0e7c806a27edd9331e5ef37 with the request logs reporting `app_engine_release=1.9.64`.

**Comment by davidwtbuxton** [comment]
@seawolf42 Thanks for bug report. I've reverted the changes and re-opened the ticket for the original feature request ( #1100 ).

**Comment by seawolf42** [comment]
@jacobg sorry about the disruption, and thanks for the suggested fix.
