### ISSUE TITLE
ImportError: No module named fcntl

### ISSUE THREAD

**Issue by simbha** [potatolondon/djangae#150]
I'm getting the following error 
#### ImportError: No module named fcntl 
on google app-engine ver-1.9.15 windows 8.1 X64 bit.
```
2015-01-03 08:33:51 Running command: "['C:\\Python27\\pythonw.exe', 'C:\\Program Files (x86)\\Google\\google_appengine\\dev_appserver.py', '--skip_sdk_update_check=yes', '--port=8080', '--admin_port=8000', u'E:\\kkk\\LAB']"
Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\google_appengine\dev_appserver.py", line 83, in <module>
    _run_file(__file__, globals())
  File "C:\Program Files (x86)\Google\google_appengine\dev_appserver.py", line 79, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\devappserver2\devappserver2.py", line 997, in <module>
    main()
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\devappserver2\devappserver2.py", line 990, in main
    dev_server.start(options)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\devappserver2\devappserver2.py", line 734, in start
    options.config_paths, options.app_id)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\devappserver2\application_configuration.py", line 751, in __init__
    module_configuration = ModuleConfiguration(config_path, app_id)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\devappserver2\application_configuration.py", line 119, in __init__
    self._config_path)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\devappserver2\application_configuration.py", line 367, in _parse_configuration
    config, files = appinfo_includes.ParseAndReturnIncludePaths(f)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\api\appinfo_includes.py", line 82, in ParseAndReturnIncludePaths
    appyaml = appinfo.LoadSingleAppInfo(appinfo_file)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\api\appinfo.py", line 2025, in LoadSingleAppInfo
    listener.Parse(app_info)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\api\yaml_listener.py", line 227, in Parse
    self._HandleEvents(self._GenerateEventParameters(stream, loader_class))
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\api\yaml_listener.py", line 178, in _HandleEvents
    raise yaml_errors.EventError(e, event_object)
google.appengine.api.yaml_errors.EventError: Unable to assign value 'your_project_id_here' to attribute 'application':
Value 'your_project_id_here' for application does not match expression '^(?:(?:[a-z\d\-]{1,100}\~)?(?:(?!\-)[a-z\d\-\.]{1,100}:)?(?!-)[a-z\d\-]{0,99}[a-z\d])$'
  in "E:\kkk\LAB\app.yaml", line 1, column 14
2015-01-03 08:34:05 (Process exited with code 1)

2015-01-03 08:35:03 Running command: "['C:\\Python27\\pythonw.exe', 'C:\\Program Files (x86)\\Google\\google_appengine\\dev_appserver.py', '--skip_sdk_update_check=yes', '--port=8080', '--admin_port=8000', u'E:\\kkk\\LAB']"
INFO     2015-01-03 08:35:06,509 devappserver2.py:745] Skipping SDK update check.
WARNING  2015-01-03 08:35:06,848 simple_search_stub.py:1115] Could not read search indexes from c:\users\john\appdata\local\temp\appengine.jrt-jango-rango-tango\search_indexes
INFO     2015-01-03 08:35:06,865 api_server.py:172] Starting API server at: http://localhost:61488
INFO     2015-01-03 08:35:06,877 dispatcher.py:185] Starting module "default" running at: http://localhost:8080
INFO     2015-01-03 08:35:06,887 admin_server.py:118] Starting admin server at: http://localhost:8000
ERROR    2015-01-03 16:35:19,651 wsgi.py:263] 

Traceback (most recent call last):

  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py", line 240, in Handle

    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())

  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py", line 299, in _LoadHandler

    handler, path, err = LoadObject(self._handler)

  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py", line 96, in LoadObject

    __import__(cumulative_path)

  File "E:\kkk\LAB\jango\wsgi.py", line 13, in <module>

    from django.core.wsgi import get_wsgi_application

ImportError: No module named django.core.wsgi

INFO     2015-01-03 08:35:19,660 module.py:709] default: "GET / HTTP/1.1" 500 -
INFO     2015-01-03 08:35:56,835 module.py:387] Detected file changes:
  -
INFO     2015-01-03 08:36:01,832 module.py:387] Detected file changes:
  -
INFO     2015-01-03 08:36:23,940 module.py:387] Detected file changes:
  -
ERROR    2015-01-03 16:36:23,961 wsgi.py:263] 

Traceback (most recent call last):

  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py", line 240, in Handle

    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())

  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py", line 299, in _LoadHandler

    handler, path, err = LoadObject(self._handler)

  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py", line 96, in LoadObject

    __import__(cumulative_path)

  File "E:\kkk\LAB\jango\wsgi.py", line 17, in <module>

    from djangae.wsgi import DjangaeApplication

ImportError: No module named djangae.wsgi

INFO     2015-01-03 08:36:23,973 module.py:709] default: "GET / HTTP/1.1" 500 -
INFO     2015-01-03 08:37:03,358 module.py:387] Detected file changes:
  -
ERROR    2015-01-03 16:37:20,266 wsgi.py:263] 

Traceback (most recent call last):

  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py", line 240, in Handle

    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())

  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py", line 299, in _LoadHandler

    handler, path, err = LoadObject(self._handler)

  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py", line 96, in LoadObject

    __import__(cumulative_path)

  File "E:\kkk\LAB\jango\wsgi.py", line 19, in <module>

    application = DjangaeApplication(get_wsgi_application())

  File "E:\kkk\LAB\djangae\wsgi.py", line 96, in __init__

    raise ImproperlyConfigured("You must place 'djangae' after 'django' apps in installed apps")

ImproperlyConfigured: You must place 'djangae' after 'django' apps in installed apps

INFO     2015-01-03 08:37:20,275 module.py:709] default: "GET / HTTP/1.1" 500 -
INFO     2015-01-03 08:37:20,424 module.py:387] Detected file changes:
  -
INFO     2015-01-03 08:37:51,424 module.py:387] Detected file changes:
  -
INFO     2015-01-03 08:37:52,483 module.py:387] Detected file changes:
  -
E:\kkk\LAB\djangae\wsgi.py:26: DeprecationWarning: Subprocess support on dev_appserver will be removed soon. Mediagenerator/assetpipe users should find alternatives which run in a separate process.

  DeprecationWarning



WARNING  2015-01-03 16:37:57,239 wsgi.py:26] E:\kkk\LAB\djangae\wsgi.py:26: DeprecationWarning: Subprocess support on dev_appserver will be removed soon. Mediagenerator/assetpipe users should find alternatives which run in a separate process.

  DeprecationWarning



ERROR    2015-01-03 16:37:57,644 wsgi.py:279] 

Traceback (most recent call last):

  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py", line 267, in Handle

    result = handler(dict(self._environ), self._StartResponse)

INFO     2015-01-03 08:37:57,654 module.py:387] Detected file changes:
  -
  File "E:\kkk\LAB\djangae\wsgi.py", line 104, in __call__

    return self.wrapped_app(environ, start_response)

  File "E:\kkk\LAB\django\core\handlers\wsgi.py", line 206, in __call__

    response = self.get_response(request)

  File "E:\kkk\LAB\django\core\handlers\base.py", line 194, in get_response

    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())

  File "E:\kkk\LAB\django\core\handlers\base.py", line 229, in handle_uncaught_exception

    return debug.technical_500_response(request, *exc_info)

  File "E:\kkk\LAB\django\views\debug.py", line 69, in technical_500_response

    html = reporter.get_traceback_html()

  File "E:\kkk\LAB\django\views\debug.py", line 323, in get_traceback_html

    c = Context(self.get_traceback_data())

  File "E:\kkk\LAB\django\views\debug.py", line 305, in get_traceback_data

    'django_version_info': get_version(),

  File "E:\kkk\LAB\django\__init__.py", line 6, in get_version

    from django.utils.version import get_version

  File "E:\kkk\LAB\django\utils\version.py", line 5, in <module>

    import subprocess

  File "C:\Python27\lib\subprocess.py", line 429, in <module>

    import fcntl

ImportError: No module named fcntl

INFO     2015-01-03 08:37:57,667 module.py:709] default: "GET / HTTP/1.1" 500 -
```

I googled "fcntl" used https://communities.cisco.com/servlet/JiveServlet/download/150596-65641/fcntl.py.zip from http://stackoverflow.com/a/25471508 but, then I got a different error : 
in submodule as 
#### AttributeError: 'module' object has no attribute 'WIFSIGNALED'
```

ERROR    2015-01-03 16:53:31,605 wsgi.py:279] 

Traceback (most recent call last):

  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py", line 267, in Handle

    result = handler(dict(self._environ), self._StartResponse)

  File "E:\kkk\LAB\djangae\wsgi.py", line 104, in __call__

    return self.wrapped_app(environ, start_response)

  File "E:\kkk\LAB\django\core\handlers\wsgi.py", line 206, in __call__

    response = self.get_response(request)

  File "E:\kkk\LAB\django\core\handlers\base.py", line 194, in get_response

    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())

  File "E:\kkk\LAB\django\core\handlers\base.py", line 229, in handle_uncaught_exception

    return debug.technical_500_response(request, *exc_info)

  File "E:\kkk\LAB\django\views\debug.py", line 69, in technical_500_response

    html = reporter.get_traceback_html()

  File "E:\kkk\LAB\django\views\debug.py", line 323, in get_traceback_html

    c = Context(self.get_traceback_data())

  File "E:\kkk\LAB\django\views\debug.py", line 305, in get_traceback_data

    'django_version_info': get_version(),

  File "E:\kkk\LAB\django\__init__.py", line 6, in get_version

    from django.utils.version import get_version

  File "E:\kkk\LAB\django\utils\version.py", line 5, in <module>

    import subprocess

  File "C:\Python27\lib\subprocess.py", line 647, in <module>

    class Popen(object):

  File "C:\Python27\lib\subprocess.py", line 1330, in Popen

    def _handle_exitstatus(self, sts, _WIFSIGNALED=os.WIFSIGNALED,

AttributeError: 'module' object has no attribute 'WIFSIGNALED'

INFO     2015-01-03 08:53:31,615 module.py:709] default: "GET / HTTP/1.1" 500 -
INFO     2015-01-03 08:53:32,219 module.py:387] Detected file changes:
  -
```

**Comment by Kazade** [comment]
I'm pretty sure this isn't a Djangae bug. Your original error is this:

    Unable to assign value 'your_project_id_here' to attribute 'application':
    Value 'your_project_id_here' for application does not match expression '^(?:(?:[a-z\d\-]{1,100}\~)?(?:(?!\-)[a-z\d\-\.]{1,100}:)?(?!-)[a-z\d\-]{0,99}[a-z\d])$'

Because you have an invalid application ID in your app.yaml file. From then on all your problems are coming from Django or Python, and not Djangae code. I'm not sure what's causing those or how to fix them though...
