### ISSUE TITLE
ImportError: cannot import name UnavailableApp

### ISSUE THREAD

**Issue by simbha** [potatolondon/djangae#152]
HI, ran into an error UnavailableApp. I've kept the database settings.py blank NUL. did not configured the database .. looking forward & thinking of useing NDB from google or sqlite3 .. 
```
simon@algby-inc:~/web-app-lab$ google_appengine/dev_appserver.py V-12/assholeUS
INFO     2015-01-07 15:00:39,051 sdk_update_checker.py:229] Checking for updates to the SDK.
INFO     2015-01-07 15:00:39,485 sdk_update_checker.py:273] This SDK release is newer than the advertised release.
INFO     2015-01-07 15:00:39,521 api_server.py:172] Starting API server at: http://localhost:46980
INFO     2015-01-07 15:00:39,685 dispatcher.py:186] Starting module "default" running at: http://localhost:8080
INFO     2015-01-07 15:00:39,686 admin_server.py:118] Starting admin server at: http://localhost:8000
ERROR    2015-01-07 15:00:43,294 wsgi.py:263] 
Traceback (most recent call last):
  File "/home/simon/web-app-lab/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/home/simon/web-app-lab/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/home/simon/web-app-lab/google_appengine/google/appengine/runtime/wsgi.py", line 96, in LoadObject
    __import__(cumulative_path)
  File "/home/simon/web-app-lab/V-12/assholeUS/assholeUS/wsgi.py", line 18, in <module>
    application = DjangaeApplication(get_wsgi_application())
  File "/home/simon/web-app-lab/V-12/assholeUS/django/core/wsgi.py", line 14, in get_wsgi_application
    django.setup()
  File "/home/simon/web-app-lab/V-12/assholeUS/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/simon/web-app-lab/V-12/assholeUS/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/simon/web-app-lab/V-12/assholeUS/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/simon/web-app-lab/V-12/assholeUS/djangae/models.py", line 10, in <module>
    patches.patch()
  File "/home/simon/web-app-lab/V-12/assholeUS/djangae/patches/__init__.py", line 6, in patch
    from . import contenttypes
  File "/home/simon/web-app-lab/V-12/assholeUS/djangae/patches/contenttypes.py", line 8, in <module>
    from django.db.models import get_model, get_models, UnavailableApp, signals, Manager, get_apps
ImportError: cannot import name UnavailableApp
INFO     2015-01-07 15:00:43,299 module.py:718] default: "GET / HTTP/1.1" 500 -
```

**Comment by Kazade** [comment]
Hmm, which version of Django are you using? Only 1.6 is supported at the moment, and UnavailableApp wasn't available in < 1.5 IIRC

**Comment by simbha** [comment]
oh! ok .. I'm current checking it with the latest release django 1.7.2. on windows 8 x64 ,python 2.7 64 & google app-engine version 1.9.15 kinda exiting..
I'll do check with django 1.6 I'm sure it'll run smooth on it. I'd manage to get it running on debian without any error.
On my second run today I got a different error RuntimeError: populate() isn't reentrant
here's the traceback of it. this was on windows 8

```
2015-01-08 10:52:07 Running command: "['C:\\Python27\\pythonw.exe', 'C:\\Program Files (x86)\\Google\\google_appengine\\dev_appserver.py', '--skip_sdk_update_check=yes', '--port=9080', '--admin_port=8001', u'K:\\prototype_\\reichstag\\archive']"
INFO     2015-01-08 10:52:08,670 devappserver2.py:745] Skipping SDK update check.
WARNING  2015-01-08 10:52:08,888 simple_search_stub.py:1115] Could not read search indexes from c:\users\john\appdata\local\temp\appengine.prototypedgae-v\search_indexes
INFO     2015-01-08 10:52:08,911 api_server.py:172] Starting API server at: http://localhost:56611
INFO     2015-01-08 10:52:08,923 dispatcher.py:185] Starting module "default" running at: http://localhost:9080
INFO     2015-01-08 10:52:08,934 admin_server.py:118] Starting admin server at: http://localhost:8001
ERROR    2015-01-08 18:52:11,532 wsgi.py:263] 

Traceback (most recent call last):

  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py", line 240, in Handle

    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())

  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py", line 299, in _LoadHandler

    handler, path, err = LoadObject(self._handler)

  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py", line 96, in LoadObject

    __import__(cumulative_path)

  File "K:\prototype_\reichstag\archive\algby\wsgi.py", line 21, in <module>

    application = DjangaeApplication(get_wsgi_application())

  File "K:\prototype_\reichstag\archive\algby\../lib\django\core\wsgi.py", line 14, in get_wsgi_application

    django.setup()

  File "K:\prototype_\reichstag\archive\algby\../lib\django\__init__.py", line 21, in setup

    apps.populate(settings.INSTALLED_APPS)

  File "K:\prototype_\reichstag\archive\algby\../lib\django\apps\registry.py", line 108, in populate

    app_config.import_models(all_models)

  File "K:\prototype_\reichstag\archive\algby\../lib\django\apps\config.py", line 202, in import_models

    self.models_module = import_module(models_module_name)

  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module

    __import__(name)

  File "K:\prototype_\reichstag\archive\algby\../lib\django\contrib\auth\models.py", line 40, in <module>

    class Permission(models.Model):

  File "K:\prototype_\reichstag\archive\algby\../lib\django\db\models\base.py", line 122, in __new__

    new_class.add_to_class('_meta', Options(meta, **kwargs))

  File "K:\prototype_\reichstag\archive\algby\../lib\django\db\models\base.py", line 297, in add_to_class

    value.contribute_to_class(cls, name)

  File "K:\prototype_\reichstag\archive\algby\../lib\django\db\models\options.py", line 166, in contribute_to_class

    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())

  File "K:\prototype_\reichstag\archive\algby\../lib\django\db\__init__.py", line 40, in __getattr__

    return getattr(connections[DEFAULT_DB_ALIAS], item)

  File "K:\prototype_\reichstag\archive\algby\../lib\django\db\utils.py", line 242, in __getitem__

    backend = load_backend(db['ENGINE'])

  File "K:\prototype_\reichstag\archive\algby\../lib\django\db\utils.py", line 108, in load_backend

    return import_module('%s.base' % backend_name)

  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module

    __import__(name)

  File "K:\prototype_\reichstag\archive\algby\../lib\django\db\backends\sqlite3\base.py", line 38, in <module>

    raise ImproperlyConfigured("Error loading either pysqlite2 or sqlite3 modules (tried in that order): %s" % exc)

ImproperlyConfigured: Error loading either pysqlite2 or sqlite3 modules (tried in that order): No module named _sqlite3

INFO     2015-01-08 10:52:11,543 module.py:709] default: "GET / HTTP/1.1" 500 -
ERROR    2015-01-08 18:52:11,578 wsgi.py:263] 

Traceback (most recent call last):

  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py", line 240, in Handle

    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())

  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py", line 299, in _LoadHandler

    handler, path, err = LoadObject(self._handler)

  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py", line 96, in LoadObject

    __import__(cumulative_path)

  File "K:\prototype_\reichstag\archive\algby\wsgi.py", line 21, in <module>

    application = DjangaeApplication(get_wsgi_application())

  File "K:\prototype_\reichstag\archive\algby\../lib\django\core\wsgi.py", line 14, in get_wsgi_application

    django.setup()

  File "K:\prototype_\reichstag\archive\algby\../lib\django\__init__.py", line 21, in setup

    apps.populate(settings.INSTALLED_APPS)

  File "K:\prototype_\reichstag\archive\algby\../lib\django\apps\registry.py", line 78, in populate

    raise RuntimeError("populate() isn't reentrant")

RuntimeError: populate() isn't reentrant

INFO     2015-01-08 10:52:11,584 module.py:709] default: "GET /favicon.ico HTTP/1.1" 500 -
ERROR    2015-01-08 18:52:11,644 wsgi.py:263] 

Traceback (most recent call last):

  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py", line 240, in Handle

    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())

  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py", line 299, in _LoadHandler

    handler, path, err = LoadObject(self._handler)

  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py", line 96, in LoadObject

    __import__(cumulative_path)

  File "K:\prototype_\reichstag\archive\algby\wsgi.py", line 21, in <module>

    application = DjangaeApplication(get_wsgi_application())

  File "K:\prototype_\reichstag\archive\algby\../lib\django\core\wsgi.py", line 14, in get_wsgi_application

    django.setup()

  File "K:\prototype_\reichstag\archive\algby\../lib\django\__init__.py", line 21, in setup

    apps.populate(settings.INSTALLED_APPS)

  File "K:\prototype_\reichstag\archive\algby\../lib\django\apps\registry.py", line 78, in populate

    raise RuntimeError("populate() isn't reentrant")

RuntimeError: populate() isn't reentrant

INFO     2015-01-08 10:52:11,648 module.py:709] default: "GET /favicon.ico HTTP/1.1" 500 -
INFO     2015-01-08 10:52:11,884 module.py:387] Detected file changes:
  -

```

**Comment by github-account-because-they-want-it** [comment]
I had that error because `djangae` was trying to import `UnavailableApp` from `django.db.models`. I fixed it in the source to import from `django.db.models.loading` instead and it worked.

**Comment by olasitarska** [comment]
It's also fixed in Djangae for [some time now](https://github.com/potatolondon/djangae/commit/b1390eaa), closing this :)

Thanks for submitting a bug report!
