### ISSUE TITLE
TypeError when doing manage.py runserver with App Engine SDK 1.9.22

### ISSUE THREAD

**Issue by davidwtbuxton** [potatolondon/djangae#372]
Trying to run the Django development server, I get a TypeError exception. This is using the current head of master, revision 3ccebb4e15a23db0968084302035961adb97605b, with App Engine SDK 1.9.22.

Using SDK 1.9.21 works fine with the same version of Djangae. Guess Google have helpfully changed their function arguments again.

    $ python manage.py runserver
    Traceback (most recent call last):
      File "manage.py", line 13, in <module>
        execute_from_command_line(sys.argv)
      File "/Users/dbuxton/Documents/Development/my-project/my-project/libs/djangae/core/management/__init__.py", line 42, in execute_from_command_line
        return _execute_from_command_line(namespace.sandbox, ['manage.py'] + namespace.args, **overrides)
      File "/Users/dbuxton/Documents/Development/my-project/my-project/libs/djangae/core/management/__init__.py", line 20, in _execute_from_command_line
        with sandbox.activate(sandbox_name, add_sdk_to_path=True, **sandbox_overrides):
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
        return self.gen.next()
      File "/Users/dbuxton/Documents/Development/my-project/my-project/libs/djangae/sandbox.py", line 322, in activate
        with SANDBOXES[sandbox_name](**kwargs):
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
        return self.gen.next()
      File "/Users/dbuxton/Documents/Development/my-project/my-project/libs/djangae/sandbox.py", line 152, in _local
        dispatcher = _create_dispatcher(configuration, options)
      File "/Users/dbuxton/Documents/Development/my-project/my-project/libs/djangae/sandbox.py", line 100, in _create_dispatcher
        _create_dispatcher.singleton = dispatcher.Dispatcher(*dispatcher_args)
    TypeError: __init__() takes exactly 18 arguments (17 given)

**Comment by Kazade** [comment]
Fixed in aecb02e
