### ISSUE TITLE
Mappers don't work on models with non-integer PKs

### ISSUE THREAD

**Issue by adamalton** [potatolondon/djangae#407]
I discovered this when using `djangae.contrib.uniquetool` (which uses `djangae.contrib.mappers`), and I think it's an issue with the mappers stuff.

If your model's primary key is not an integer-ish field then you get this error:

```
Internal Server Error: /_ah/mapreduce/kickoffjob_callback/1574160994066DC1D0E2C (/base/data/home/apps/s~my-project/57-df974ea24d-stable.386079706619870743/sitepackages/django/core/handlers/base.py:231)
Traceback (most recent call last):
  File "/base/data/home/apps/s~my-project/57-df974ea24d-stable.386079706619870743/sitepackages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/base/data/home/apps/s~my-project/57-df974ea24d-stable.386079706619870743/sitepackages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/base/data/home/apps/s~my-project/57-df974ea24d-stable.386079706619870743/sitepackages/djangae/utils.py", line 173, in request_handler_wrapper
    view_func.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~my-project/57-df974ea24d-stable.386079706619870743/sitepackages/mapreduce/base_handler.py", line 131, in post
    self.handle()
  File "/base/data/home/apps/s~my-project/57-df974ea24d-stable.386079706619870743/sitepackages/mapreduce/handlers.py", line 1365, in handle
    readers, serialized_readers_entity = self._get_input_readers(state)
  File "/base/data/home/apps/s~my-project/57-df974ea24d-stable.386079706619870743/sitepackages/mapreduce/handlers.py", line 1437, in _get_input_readers
    readers = input_reader_class.split_input(split_param)
  File "/base/data/home/apps/s~my-project/57-df974ea24d-stable.386079706619870743/sitepackages/djangae/contrib/mappers/readers.py", line 76, in split_input
    pk_range = last_id - first_id
TypeError: unsupported operand type(s) for -: 'unicode' and 'unicode'
```

**Comment by nealedj** [comment]
It's worth noting that the reader in [this branch](https://github.com/chargrizzle/djangae/blob/pipelines/djangae/contrib/mapreduce/input_readers.py) appears to work with unicode PKs.
