### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'SelectCommand' objects

### ISSUE THREAD

**Issue by chargrizzle** [potatolondon/djangae#435]
```python
pks = Model.objects.all().values_list("pk", flat=True)
questions = Model.objects.filter(pk__in=pks)
```
```
Traceback (most recent call last):
 File "{PATH}/django/core/handlers/base.py", line 132, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/home/charlie/src/echo/src/echo/views.py", line 35, in playlist_reorder
   for question in questions:
 File "{PATH}/django/db/models/query.py", line 162, in __iter__
   self._fetch_all()
 File "{PATH}/django/db/models/query.py", line 965, in _fetch_all
   self._result_cache = list(self.iterator())
 File "{PATH}/django/db/models/query.py", line 238, in iterator
   results = compiler.execute_sql()
 File "{PATH}/django/db/models/sql/compiler.py", line 829, in execute_sql
   sql, params = self.as_sql()
 File "{PATH}/djangae/db/backends/appengine/compiler.py", line 30, in as_sql
   self.query
 File "{PATH}/djangae/db/backends/appengine/commands.py", line 335, in __init__
   self.query = transform_query(connection, query)
 File "{PATH}/djangae/db/backends/appengine/query.py", line 1145, in transform_query
   return _FACTORY[version](connection, kind, query)
 File "{PATH}/djangae/db/backends/appengine/query.py", line 1096, in _transform_query_18
   model=query.model
 File "{PATH}/djangae/db/backends/appengine/query.py", line 899, in _walk_django_where
   walk_node(query.where, **kwargs)
 File "{PATH}/djangae/db/backends/appengine/query.py", line 889, in walk_node
   leaf_callback(child, **new_kwargs)
 File "{PATH}/djangae/db/backends/appengine/query.py", line 929, in _django_17_query_walk_leaf
   rhs = node.process_rhs(None, connection)
 File "{PATH}/django/db/models/lookups.py", line 276, in process_rhs
   return super(In, self).process_rhs(compiler, connection)
 File "{PATH}/django/db/models/lookups.py", line 171, in process_rhs
   return '(' + sql + ')', params
TypeError: cannot concatenate 'str' and 'SelectCommand' objects 
```

Should be caught

**Comment by adamalton** [comment]
I think this is because `pks` is still an unevaluated queryset, and so when you pass it into `filter(pk__in=pks)` Django tries to combine the 2 queries to make a clever `JOIN`.

But yeah, a more meaningful error message (probably `NotSupportedError`) would be good.
