### ISSUE TITLE
Handling F() expression when updating

### ISSUE THREAD

**Issue by ana-balica** [potatolondon/djangae#441]
I'm trying to increment a model field value using F() expression. Suppose I have `Foo` model that has a `position` field.

```python
from django.db import models
from foo_app.models import Foo

queryset = Foo.objects.all()
queryset.update(position=models.F('position') + 1)
```

This fails with the following traceback:
```
ERROR    2015-09-08 12:17:28,565 base.py:256] Internal Server Error: /checklist/ana5/check/5166673858396160/position/
Traceback (most recent call last):
  File "/Users/abalica/Workspace/checker/src/sitepackages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abalica/Workspace/checker/src/sitepackages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/Users/abalica/Workspace/checker/src/checker/views.py", line 219, in position_check
    check.save()
  File "/Users/abalica/Workspace/checker/src/checker/models.py", line 106, in save
    super(Check, self).save(*args, **kwargs)
  File "/Users/abalica/Workspace/checker/src/sitepackages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/abalica/Workspace/checker/src/sitepackages/django/db/models/base.py", line 771, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/Users/abalica/Workspace/checker/src/sitepackages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/abalica/Workspace/checker/src/sitepackages/positions/fields.py", line 254, in update_on_save
    queryset.update(**updates)
  File "/Users/abalica/Workspace/checker/src/sitepackages/django/db/models/query.py", line 563, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/Users/abalica/Workspace/checker/src/sitepackages/django/db/models/sql/compiler.py", line 1062, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/Users/abalica/Workspace/checker/src/sitepackages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/Users/abalica/Workspace/checker/src/sitepackages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/abalica/Workspace/checker/src/sitepackages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/abalica/Workspace/checker/src/sitepackages/djangae/db/backends/appengine/base.py", line 103, in execute
    self.rowcount = sql.execute()
  File "/Users/abalica/Workspace/checker/src/sitepackages/djangae/db/backends/appengine/commands.py", line 968, in execute
    if self._update_entity(result.key()):
  File "/Users/abalica/Workspace/checker/third_party/google_appengine/google/appengine/api/datastore.py", line 2732, in inner_wrapper
    return RunInTransactionOptions(options, func, *args, **kwds)
  File "/Users/abalica/Workspace/checker/third_party/google_appengine/google/appengine/api/datastore.py", line 2630, in RunInTransactionOptions
    ok, result = _DoOneTry(function, args, kwargs)
  File "/Users/abalica/Workspace/checker/third_party/google_appengine/google/appengine/api/datastore.py", line 2650, in _DoOneTry
    result = function(*args, **kwargs)
  File "/Users/abalica/Workspace/checker/src/sitepackages/djangae/db/backends/appengine/commands.py", line 927, in _update_entity
    True, instance)
  File "/Users/abalica/Workspace/checker/src/sitepackages/djangae/db/utils.py", line 176, in django_instance_to_entity
    value, is_primary_key = value_from_instance(instance, field)
  File "/Users/abalica/Workspace/checker/src/sitepackages/djangae/db/utils.py", line 154, in value_from_instance
    value = get_prepared_db_value(connection, _instance, _field, raw)
  File "/Users/abalica/Workspace/checker/src/sitepackages/djangae/db/utils.py", line 103, in get_prepared_db_value
    connection=connection
  File "/Users/abalica/Workspace/checker/src/sitepackages/django/db/models/fields/__init__.py", line 710, in get_db_prep_save
    prepared=False)
  File "/Users/abalica/Workspace/checker/src/sitepackages/django/db/models/fields/__init__.py", line 702, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/Users/abalica/Workspace/checker/src/sitepackages/django/db/models/fields/__init__.py", line 1868, in get_prep_value
    return int(value)
TypeError: int() argument must be a string or a number, not 'CombinedExpression'
```

**Comment by Kazade** [comment]
Although on the datastore this is no different than fetching, doing the increment, and putting again, we should support these F expressions just for syntactic sugar and to maintain the abstraction.

This should be doable using the existing annotations framework
