### ISSUE TITLE
Problem flush/clearing datastore

### ISSUE THREAD

**Issue by matto1990** [potatolondon/djangae#489]
I'm looking to clear the datastore of all data while in development. It seems that `./manage.py` has a `flush` command, but this produces and `IntegrityError` when running it using Djangae:

```
(env)$ ./manage.py flush --no-initial-data
INFO     2015-11-25 15:30:40,666 blobstore_service.py:70] Starting blobstore service on localhost:8080
WARNING  2015-11-25 15:30:40,669 blobstore_service.py:74] Not starting blobstore service, it may already be running
You have requested a flush of the database.
This will IRREVERSIBLY DESTROY all data currently in the '' database,
and return each table to an empty state.
Are you sure you want to do this?

    Type 'yes' to continue, or 'no' to cancel: yes
Traceback (most recent call last):
  File "./manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "SNIP/sitepackages/djangae/core/management/__init__.py", line 65, in execute_from_command_line
    return _execute_from_command_line(namespace.sandbox, ['manage.py'] + namespace.args, **overrides)
  File "SNIP/sitepackages/djangae/core/management/__init__.py", line 45, in _execute_from_command_line
    return django_management.execute_from_command_line(argv)
  File "SNIP/sitepackages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "SNIP/sitepackages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "SNIP/sitepackages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "SNIP/sitepackages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "SNIP/sitepackages/django/core/management/commands/flush.py", line 84, in handle
    self.emit_post_migrate(verbosity, interactive, database)
  File "SNIP/sitepackages/django/core/management/commands/flush.py", line 105, in emit_post_migrate
    emit_post_migrate_signal(set(all_models), verbosity, interactive, database)
  File "SNIP/sitepackages/django/core/management/sql.py", line 280, in emit_post_migrate_signal
    using=db)
  File "SNIP/sitepackages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "SNIP/sitepackages/django/contrib/contenttypes/management.py", line 53, in update_contenttypes
    ContentType.objects.using(using).bulk_create(cts)
  File "SNIP/sitepackages/django/db/models/query.py", line 392, in bulk_create
    self._batched_insert(objs_without_pk, fields, batch_size)
  File "SNIP/sitepackages/django/db/models/query.py", line 937, in _batched_insert
    using=self.db)
  File "SNIP/sitepackages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "SNIP/sitepackages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "SNIP/sitepackages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "SNIP/sitepackages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "SNIP/sitepackages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "SNIP/sitepackages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "SNIP/sitepackages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "SNIP/sitepackages/djangae/db/backends/appengine/base.py", line 102, in execute
    self.returned_ids = sql.execute()
  File "SNIP/sitepackages/djangae/db/backends/appengine/commands.py", line 849, in execute
    markers = constraints.acquire_bulk(self.model, self.entities)
  File "SNIP/sitepackages/djangae/db/constraints.py", line 127, in acquire_bulk
    markers.append(acquire(model, entity))
  File "SNIP/sitepackages/djangae/db/constraints.py", line 143, in acquire
    return acquire_identifiers(identifiers, entity.key())
  File "SNIP/sitepackages/djangae/db/constraints.py", line 84, in acquire_identifiers
    markers.append(acquire_marker(identifier))
  File "SNIP/sitepackages/google_appengine/google/appengine/api/datastore.py", line 2732, in inner_wrapper
    return RunInTransactionOptions(options, func, *args, **kwds)
  File "SNIP/sitepackages/google_appengine/google/appengine/api/datastore.py", line 2630, in RunInTransactionOptions
    ok, result = _DoOneTry(function, args, kwargs)
  File "SNIP/sitepackages/google_appengine/google/appengine/api/datastore.py", line 2650, in _DoOneTry
    result = function(*args, **kwargs)
  File "SNIP/sitepackages/djangae/db/constraints.py", line 68, in acquire_marker
    raise IntegrityError("Unable to acquire marker for %s" % identifier)
django.db.utils.IntegrityError: Unable to acquire marker for django_content_type|app_label:43b5ea97ae60cce57306752176aa894a|model:cda21231a58be8212c63e2872054ef1b
```

I used the [Djangae scafold](https://github.com/potatolondon/djangae-scaffold) to start the project.

If this command is not designed to be used for Djangae projects, what is the best way to clear the Datastore while in development. Currently I'm manually clearing all entries using the web interface, which is fine, but not very efficient.

**Comment by Kazade** [comment]
Hmm, the problem is that the default content types signals don't work with eventually consistent queries. What's happening here is the flush is working, but then the content types signal is trying to create a duplicate content type and our unique marker checks are throwing.

We have a patch in Djangae which replaces this code with a safer version for the datastore (https://github.com/potatolondon/djangae/blob/master/djangae/patches/contenttypes.py#L190) but I'm not sure why that patch isn't being applied for you.

@adamalton related... should we consider doing key lookups on unique markers when someone queries on unique fields?

**Comment by matto1990** [comment]
I ran through trying to run flush on the basic Django scaffold project with none of the changes I've made for my project and the same error occurs. If a patch is not being applied then I can only think that it's my environment that's the issue.

Here's the full log from running flush on the basic scaffold project:

```
➜  /tmp  git clone https://github.com/potatolondon/djangae-scaffold.git
Cloning into 'djangae-scaffold'...
remote: Counting objects: 329, done.
remote: Total 329 (delta 0), reused 0 (delta 0), pack-reused 329
Receiving objects: 100% (329/329), 57.04 KiB | 0 bytes/s, done.
Resolving deltas: 100% (187/187), done.
Checking connectivity... done.
➜  /tmp  cd djangae-scaffold
➜  djangae-scaffold git:(master) ./install_deps
Creating `sitepackages` directory for dependencies...
Downloading the AppEngine SDK...
Running pip...
Collecting djangae from git+https://github.com/potatolondon/djangae.git#egg=djangae (from -r /private/tmp/djangae-scaffold/requirements.txt (line 1))
  Cloning https://github.com/potatolondon/djangae.git to /private/var/folders/02/b_gqh4m934996ktld5_6srbh0000gn/T/pip-build-EiFj_3/djangae
Collecting django<1.9,>=1.7 (from -r /private/tmp/djangae-scaffold/requirements.txt (line 2))
  Downloading Django-1.8.7-py2.py3-none-any.whl (6.2MB)
    100% |████████████████████████████████| 6.2MB 90kB/s
Collecting django-secure (from -r /private/tmp/djangae-scaffold/requirements.txt (line 3))
Collecting django-csp (from -r /private/tmp/djangae-scaffold/requirements.txt (line 4))
Collecting cspreports from git+https://github.com/adamalton/django-csp-reports.git#egg=cspreports (from -r /private/tmp/djangae-scaffold/requirements.txt (line 5))
  Cloning https://github.com/adamalton/django-csp-reports.git to /private/var/folders/02/b_gqh4m934996ktld5_6srbh0000gn/T/pip-build-EiFj_3/cspreports
Collecting django-session-csrf (from -r /private/tmp/djangae-scaffold/requirements.txt (line 6))
Collecting nose (from -r /private/tmp/djangae-scaffold/requirements.txt (line 7))
  Using cached nose-1.3.7-py2-none-any.whl
Collecting six (from -r /private/tmp/djangae-scaffold/requirements.txt (line 8))
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: djangae, django, django-secure, django-csp, cspreports, django-session-csrf, nose, six
  Running setup.py install for djangae
  Running setup.py install for cspreports
Successfully installed cspreports djangae django django-csp django-secure django-session-csrf nose six-1.4.1
➜  djangae-scaffold git:(master) ./rename_scaffold_app myapp
./app.yaml
./manage.py
./scaffold/__init__.py
./scaffold/boot.py
./scaffold/checks.py
./scaffold/settings.py
./scaffold/settings_live.py
./scaffold/urls.py
./scaffold/wsgi.py
➜  djangae-scaffold git:(master) ✗ python manage.py checksecure --settings=myapp.settings_live
WARNING  2015-11-26 10:18:18,540 simple_search_stub.py:1126] Could not read search indexes from /private/tmp/djangae-scaffold/.storage/search_indexes
INFO     2015-11-26 10:18:18,597 blobstore_service.py:70] Starting blobstore service on localhost:8080
WARNING  2015-11-26 10:18:18,605 blobstore_service.py:74] Not starting blobstore service, it may already be running
WARNING  2015-11-26 10:18:19,020 importlib.py:9] /private/tmp/djangae-scaffold/sitepackages/djangosecure/check/run.py:1: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Running djangosecure.check.sessions.check_session_cookie_secure...
OK

Running djangosecure.check.sessions.check_session_cookie_httponly...
OK

Running djangosecure.check.djangosecure.check_security_middleware...
OK

Running djangosecure.check.djangosecure.check_sts...
OK

Running djangosecure.check.djangosecure.check_frame_deny...
OK

Running djangosecure.check.djangosecure.check_ssl_redirect...
OK

Running myapp.checks.check_session_csrf_enabled...
OK

Running myapp.checks.check_csp_is_not_report_only...
OK

Running myapp.checks.check_csp_sources_not_unsafe...
OK


All clear!


➜  djangae-scaffold git:(master) ✗ python manage.py runserver
INFO     2015-11-26 10:18:39,008 blobstore_service.py:70] Starting blobstore service on localhost:8080
Validating models...

System check identified no issues (0 silenced).
November 26, 2015 - 10:18:39
Django version 1.8.7, using settings 'myapp.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

INFO     2015-11-26 10:18:39,530 devappserver2.py:762] Skipping SDK update check.
INFO     2015-11-26 10:18:39,532 api_server.py:204] Starting API server at: http://127.0.0.1:8002
INFO     2015-11-26 10:18:39,536 dispatcher.py:197] Starting module "default" running at: http://localhost:8000
INFO     2015-11-26 10:18:39,537 admin_server.py:118] Starting admin server at: http://127.0.0.1:8001
/private/tmp/djangae-scaffold/sitepackages/google_appengine/google/appengine/tools/devappserver2/mtime_file_watcher.py:115: UserWarning: There are too many files in your application for changes in all of them to be monitored. You may have to restart the development server to see some changes to your files.
  'There are too many files in your application for '

WARNING  2015-11-26 10:18:39,744 mtime_file_watcher.py:115] /private/tmp/djangae-scaffold/sitepackages/google_appengine/google/appengine/tools/devappserver2/mtime_file_watcher.py:115: UserWarning: There are too many files in your application for changes in all of them to be monitored. You may have to restart the development server to see some changes to your files.
  'There are too many files in your application for '

INFO     2015-11-26 10:18:42,183 module.py:445] [default] Detected file changes:
  /private/tmp/djangae-scaffold/sitepackages/google_appengine/google/appengine/api
  /private/tmp/djangae-scaffold/sitepackages/google_appengine/google/appengine/api/remote_socket
  /private/tmp/djangae-scaffold/sitepackages/google_appengine/google/appengine/dist27
  /private/tmp/djangae-scaffold/sitepackages/google_appengine/google/appengine/runtime
  /private/tmp/djangae-scaffold/sitepackages/google_appengine/google/appengine/tools/devappserver2
  /private/tmp/djangae-scaffold/sitepackages/google_appengine/google/appengine/tools/devappserver2/python
WARNING  2015-11-26 10:18:50,957 middleware.py:122] settings.CSRF_COOKIE_SECURE is not set to True, this is insecure
WARNING  2015-11-26 10:18:50,957 middleware.py:122] settings.SESSION_COOKIE_SECURE is not set to True, this is insecure
INFO     2015-11-26 10:18:51,020 module.py:445] [default] Detected file changes:
  /private/tmp/djangae-scaffold/myapp
  /private/tmp/djangae-scaffold/sitepackages/google_appengine/google/appengine/dist
INFO     2015-11-26 10:18:51,303 runserver.py:265] default: "GET / HTTP/1.1" 404 2218
INFO     2015-11-26 10:18:52,253 module.py:445] [default] Detected file changes:
  /private/tmp/djangae-scaffold/myapp
  /private/tmp/djangae-scaffold/sitepackages/google_appengine/google/appengine/dist27
  /private/tmp/djangae-scaffold/sitepackages/google_appengine/google/appengine/dist27/gae_override
  /private/tmp/djangae-scaffold/sitepackages/google_appengine/google/appengine/ext/deferred
  /private/tmp/djangae-scaffold/sitepackages/google_appengine/lib/webapp2-2.3
WARNING  2015-11-26 10:18:53,382 middleware.py:122] settings.CSRF_COOKIE_SECURE is not set to True, this is insecure
WARNING  2015-11-26 10:18:53,383 middleware.py:122] settings.SESSION_COOKIE_SECURE is not set to True, this is insecure
WARNING  2015-11-26 10:18:53,438 utils.py:49] Content Security Policy violation: {
    "csp-report": {
        "blocked-uri": "",
        "document-uri": "http://localhost:8000/",
        "effective-directive": "style-src",
        "original-policy": "connect-src 'self' plus.google.com www.google-analytics.com; img-src 'self' data: s.ytimg.com *.googleusercontent.com *.gstatic.com; default-src 'self' *.gstatic.com; font-src 'self' themes.googleusercontent.com *.gstatic.com; frame-src 'self' www.google.com www.youtube.com accounts.google.com apis.google.com plus.google.com; script-src 'self' *.googleanalytics.com *.google-analytics.com ajax.googleapis.com; style-src 'self' fonts.googleapis.com *.gstatic.com; report-uri /csp/report/",
        "referrer": "",
        "status-code": 404,
        "violated-directive": "style-src 'self' fonts.googleapis.com *.gstatic.com"
    }
}
INFO     2015-11-26 10:18:53,455 runserver.py:265] default: "POST /csp/report/ HTTP/1.1" 200 -
WARNING  2015-11-26 10:18:53,533 middleware.py:122] settings.CSRF_COOKIE_SECURE is not set to True, this is insecure
WARNING  2015-11-26 10:18:53,533 middleware.py:122] settings.SESSION_COOKIE_SECURE is not set to True, this is insecure
WARNING  2015-11-26 10:18:53,574 utils.py:49] Content Security Policy violation: {
    "csp-report": {
        "blocked-uri": "",
        "column-number": 10,
        "document-uri": "http://localhost:8000/",
        "effective-directive": "style-src",
        "line-number": 50,
        "original-policy": "connect-src 'self' plus.google.com www.google-analytics.com; img-src 'self' data: s.ytimg.com *.googleusercontent.com *.gstatic.com; default-src 'self' *.gstatic.com; font-src 'self' themes.googleusercontent.com *.gstatic.com; frame-src 'self' www.google.com www.youtube.com accounts.google.com apis.google.com plus.google.com; script-src 'self' *.googleanalytics.com *.google-analytics.com ajax.googleapis.com; style-src 'self' fonts.googleapis.com *.gstatic.com; report-uri /csp/report/",
        "referrer": "",
        "source-file": "chrome-extension://noojglkidnpfjbincgijbaiedldjfbhh",
        "status-code": 404,
        "violated-directive": "style-src 'self' fonts.googleapis.com *.gstatic.com"
    }
}
INFO     2015-11-26 10:18:53,590 runserver.py:265] default: "POST /csp/report/ HTTP/1.1" 200 -
^CINFO     2015-11-26 10:18:56,789 api_server.py:629] Applying all pending transactions and saving the datastore
INFO     2015-11-26 10:18:56,800 api_server.py:632] Saving search indexes
➜  djangae-scaffold git:(master) ✗ python manage.py flush
INFO     2015-11-26 10:19:03,115 blobstore_service.py:70] Starting blobstore service on localhost:8080
You have requested a flush of the database.
This will IRREVERSIBLY DESTROY all data currently in the '' database,
and return each table to an empty state.
Are you sure you want to do this?

    Type 'yes' to continue, or 'no' to cancel: yes
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/private/tmp/djangae-scaffold/sitepackages/djangae/core/management/__init__.py", line 65, in execute_from_command_line
    return _execute_from_command_line(namespace.sandbox, ['manage.py'] + namespace.args, **overrides)
  File "/private/tmp/djangae-scaffold/sitepackages/djangae/core/management/__init__.py", line 45, in _execute_from_command_line
    return django_management.execute_from_command_line(argv)
  File "/private/tmp/djangae-scaffold/sitepackages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/private/tmp/djangae-scaffold/sitepackages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/private/tmp/djangae-scaffold/sitepackages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/private/tmp/djangae-scaffold/sitepackages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/private/tmp/djangae-scaffold/sitepackages/django/core/management/commands/flush.py", line 84, in handle
    self.emit_post_migrate(verbosity, interactive, database)
  File "/private/tmp/djangae-scaffold/sitepackages/django/core/management/commands/flush.py", line 105, in emit_post_migrate
    emit_post_migrate_signal(set(all_models), verbosity, interactive, database)
  File "/private/tmp/djangae-scaffold/sitepackages/django/core/management/sql.py", line 280, in emit_post_migrate_signal
    using=db)
  File "/private/tmp/djangae-scaffold/sitepackages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/private/tmp/djangae-scaffold/sitepackages/django/contrib/contenttypes/management.py", line 53, in update_contenttypes
    ContentType.objects.using(using).bulk_create(cts)
  File "/private/tmp/djangae-scaffold/sitepackages/django/db/models/query.py", line 392, in bulk_create
    self._batched_insert(objs_without_pk, fields, batch_size)
  File "/private/tmp/djangae-scaffold/sitepackages/django/db/models/query.py", line 937, in _batched_insert
    using=self.db)
  File "/private/tmp/djangae-scaffold/sitepackages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/private/tmp/djangae-scaffold/sitepackages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/private/tmp/djangae-scaffold/sitepackages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/private/tmp/djangae-scaffold/sitepackages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/private/tmp/djangae-scaffold/sitepackages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/private/tmp/djangae-scaffold/sitepackages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/private/tmp/djangae-scaffold/sitepackages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/private/tmp/djangae-scaffold/sitepackages/djangae/db/backends/appengine/base.py", line 102, in execute
    self.returned_ids = sql.execute()
  File "/private/tmp/djangae-scaffold/sitepackages/djangae/db/backends/appengine/commands.py", line 849, in execute
    markers = constraints.acquire_bulk(self.model, self.entities)
  File "/private/tmp/djangae-scaffold/sitepackages/djangae/db/constraints.py", line 127, in acquire_bulk
    markers.append(acquire(model, entity))
  File "/private/tmp/djangae-scaffold/sitepackages/djangae/db/constraints.py", line 143, in acquire
    return acquire_identifiers(identifiers, entity.key())
  File "/private/tmp/djangae-scaffold/sitepackages/djangae/db/constraints.py", line 84, in acquire_identifiers
    markers.append(acquire_marker(identifier))
  File "/private/tmp/djangae-scaffold/sitepackages/google_appengine/google/appengine/api/datastore.py", line 2732, in inner_wrapper
    return RunInTransactionOptions(options, func, *args, **kwds)
  File "/private/tmp/djangae-scaffold/sitepackages/google_appengine/google/appengine/api/datastore.py", line 2630, in RunInTransactionOptions
    ok, result = _DoOneTry(function, args, kwargs)
  File "/private/tmp/djangae-scaffold/sitepackages/google_appengine/google/appengine/api/datastore.py", line 2650, in _DoOneTry
    result = function(*args, **kwargs)
  File "/private/tmp/djangae-scaffold/sitepackages/djangae/db/constraints.py", line 68, in acquire_marker
    raise IntegrityError("Unable to acquire marker for %s" % identifier)
django.db.utils.IntegrityError: Unable to acquire marker for django_content_type|app_label:43b5ea97ae60cce57306752176aa894a|model:cda21231a58be8212c63e2872054ef1b
```

Here's some information about my Python version. It's the default OS X Python:

```
➜  djangae-scaffold git:(master) ✗ python --version
Python 2.7.10
➜  djangae-scaffold git:(master) ✗ which python
/usr/bin/python
```

I'm not using `virtualenv` for these logs but I was in my actual project.

Hope this helps! Let me know if you need any more information or want me to try anything.

**Comment by matto1990** [comment]
Also, just to be clear: You said that _the flush is working_, however I'm not seeing any of the data being cleared from the datastore.

**Comment by olasitarska** [comment]
@matto1990 is this still an issue? please reopen if so, as we haven't had any other reports about this functionality not working.
