### ISSUE TITLE
When djangaeidx.yaml file doesn't exist queries like `__icontains` throw an error

### ISSUE THREAD

**Issue by ercchy** [potatolondon/djangae#511]
Here is the whole stack trace

```
Internal Server Error: /admin/search/
Traceback (most recent call last):
  File "/project/src/sitepackages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/project/src/sitepackages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/project/src/sitepackages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/project/src/sitepackages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/project/src/sitepackages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/project/src/sitepackages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/project/src/sitepackages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/project/src/sitepackages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/project/src/sitepackages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/project/src/sitepackages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/project/src/sitepackages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/project/src/sitepackages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/project/src/sitepackages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/project/src/sitepackages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/project/src/sitepackages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/project/src/sitepackages/django/template/defaulttags.py", line 328, in render
    if match:
  File "/project/src/sitepackages/django/db/models/query.py", line 170, in __nonzero__
    return type(self).__bool__(self)
  File "/project/src/sitepackages/django/db/models/query.py", line 166, in __bool__
    self._fetch_all()
  File "/project/src/sitepackages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/project/src/sitepackages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/project/src/sitepackages/django/db/models/sql/compiler.py", line 829, in execute_sql
    sql, params = self.as_sql()
  File "/project/src/sitepackages/djangae/db/backends/appengine/compiler.py", line 20, in as_sql
    self.query
  File "/project/src/sitepackages/djangae/db/backends/appengine/commands.py", line 392, in __init__
    self.query = transform_query(connection, query)
  File "/project/src/sitepackages/djangae/db/backends/appengine/query.py", line 1153, in transform_query
    return _FACTORY[version](connection, kind, query)
  File "/project/src/sitepackages/djangae/db/backends/appengine/query.py", line 1103, in _transform_query_18
    model=query.model
  File "/project/src/sitepackages/djangae/db/backends/appengine/query.py", line 906, in _walk_django_where
    walk_node(query.where, **kwargs)
  File "/project/src/sitepackages/djangae/db/backends/appengine/query.py", line 896, in walk_node
    leaf_callback(child, **new_kwargs)
  File "/project/src/sitepackages/djangae/db/backends/appengine/query.py", line 957, in _django_17_query_walk_leaf
    target_field=node.lhs.target,
  File "/project/src/sitepackages/djangae/db/backends/appengine/query.py", line 149, in set_leaf
    add_special_index(target_field.model, column, operator, value)
  File "/project/src/sitepackages/djangae/db/backends/appengine/indexing.py", line 103, in add_special_index
    write_special_indexes()
  File "/project/src/sitepackages/djangae/db/backends/appengine/indexing.py", line 73, in write_special_indexes
    with allow_mode_write():
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/project/src/sitepackages/djangae/sandbox.py", line 383, in allow_mode_write
    new_dirs = set(stubs.FakeFile._allowed_dirs).union({ tempfile.gettempdir() })
  File "/project/third_party/google_appengine/google/appengine/dist/tempfile.py", line 61, in PlaceHolder
    raise NotImplementedError("Only tempfile.TemporaryFile is available for use")
NotImplementedError: Only tempfile.TemporaryFile is available for use
ERROR    2015-12-08 15:40:16,175 base.py:256] Internal Server Error: /admin/search/
Traceback (most recent call last):
  File "/project/src/sitepackages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/project/src/sitepackages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/project/src/sitepackages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/project/src/sitepackages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/project/src/sitepackages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/project/src/sitepackages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/project/src/sitepackages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/project/src/sitepackages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/project/src/sitepackages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/project/src/sitepackages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/project/src/sitepackages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/project/src/sitepackages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/project/src/sitepackages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/project/src/sitepackages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/project/src/sitepackages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/project/src/sitepackages/django/template/defaulttags.py", line 328, in render
    if match:
  File "/project/src/sitepackages/django/db/models/query.py", line 170, in __nonzero__
    return type(self).__bool__(self)
  File "/project/src/sitepackages/django/db/models/query.py", line 166, in __bool__
    self._fetch_all()
  File "/project/src/sitepackages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/project/src/sitepackages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/project/src/sitepackages/django/db/models/sql/compiler.py", line 829, in execute_sql
    sql, params = self.as_sql()
  File "/project/src/sitepackages/djangae/db/backends/appengine/compiler.py", line 20, in as_sql
    self.query
  File "/project/src/sitepackages/djangae/db/backends/appengine/commands.py", line 392, in __init__
    self.query = transform_query(connection, query)
  File "/project/src/sitepackages/djangae/db/backends/appengine/query.py", line 1153, in transform_query
    return _FACTORY[version](connection, kind, query)
  File "/project/src/sitepackages/djangae/db/backends/appengine/query.py", line 1103, in _transform_query_18
    model=query.model
  File "/project/src/sitepackages/djangae/db/backends/appengine/query.py", line 906, in _walk_django_where
    walk_node(query.where, **kwargs)
  File "/project/src/sitepackages/djangae/db/backends/appengine/query.py", line 896, in walk_node
    leaf_callback(child, **new_kwargs)
  File "/project/src/sitepackages/djangae/db/backends/appengine/query.py", line 957, in _django_17_query_walk_leaf
    target_field=node.lhs.target,
  File "/project/src/sitepackages/djangae/db/backends/appengine/query.py", line 149, in set_leaf
    add_special_index(target_field.model, column, operator, value)
  File "/project/src/sitepackages/djangae/db/backends/appengine/indexing.py", line 103, in add_special_index
    write_special_indexes()
  File "/project/src/sitepackages/djangae/db/backends/appengine/indexing.py", line 73, in write_special_indexes
    with allow_mode_write():
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/project/src/sitepackages/djangae/sandbox.py", line 383, in allow_mode_write
    new_dirs = set(stubs.FakeFile._allowed_dirs).union({ tempfile.gettempdir() })
  File "/project/third_party/google_appengine/google/appengine/dist/tempfile.py", line 61, in PlaceHolder
    raise NotImplementedError("Only tempfile.TemporaryFile is available for use")
NotImplementedError: Only tempfile.TemporaryFile is available for use
INFO     2015-12-08 15:40:16,329 datastore_stub_index.py:301] Updating /project/src/index.yaml
INFO     2015-12-08 15:40:16,399 datastore_stub_index.py:301] Updating /project/src/index.yaml
INFO     2015-12-08 15:40:16,500 module.py:441] [default] Detected file changes:
  /project/src/index.yaml
ERROR    2015-12-08 15:40:16,991 commands.py:729] Unable to translate query to string
Traceback (most recent call last):
  File "/project/src/sitepackages/djangae/db/backends/appengine/commands.py", line 709, in __unicode__
    qry = json.loads(self.query.serialize())
AttributeError: 'SelectCommand' object has no attribute 'query'
INFO     2015-12-08 15:40:17,143 runserver.py:265] default: "GET /admin/search/?q=test@example.com HTTP/1.1" 500 220570
```

**Comment by Kazade** [comment]
This is a bug I introduced. We have two utility functions in sandbox.py for escaping the dev_appserver sandbox. These are `allow_modules` and `allow_mode_write`.

The latter allows writing to files, but it's also common to want to allow writing to the temporary directory when you use this context manager. Unfortunately, `gettempdir` only works if you've used `allow_mode_write` within a counterpart `allow_modules`.

We should check to see if `gettempdir` is available before adding it to the `_allowed_dirs` variable.
