### ISSUE TITLE
Error running ./manage.py migrate

### ISSUE THREAD

**Issue by yfr** [potatolondon/djangae#547]
Hey ,

I'm new to python and Django/djangae. For a project, we need to have a Django install on appEngine. As far as I understand I just need to follow everything in `djangae-scaffold` project and I can use everything like I would in Django.

The scaffold setup worked like a charm but when I start setting up my first model (from the [tutorial](https://docs.djangoproject.com/en/1.8/intro/tutorial01/) on the Django help pages) I get the following error. Can someone explain me in detail what's wrong? Thanks a lot!

```sh
15:51 $ python manage.py migrate
INFO     2016-01-07 15:51:09,484 blobstore_service.py:73] Starting blobstore service on localhost:8080
Operations to perform:
  Synchronize unmigrated apps: djangosecure, csp, datastore, djangae
  Apply all migrations: sessions, admin, auth, contenttypes, cspreports, testapp
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Running migrations:
  Applying testapp.0001_initial...Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/USER/Documents/djangae-scaffold/sitepackages/djangae/core/management/__init__.py", line 65, in execute_from_command_line
    return _execute_from_command_line(namespace.sandbox, ['manage.py'] + namespace.args, **overrides)
  File "/Users/USER/Documents/djangae-scaffold/sitepackages/djangae/core/management/__init__.py", line 45, in _execute_from_command_line
    return django_management.execute_from_command_line(argv)
  File "/Users/USER/Documents/djangae-scaffold/sitepackages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/USER/Documents/djangae-scaffold/sitepackages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/USER/Documents/djangae-scaffold/sitepackages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/USER/Documents/djangae-scaffold/sitepackages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/USER/Documents/djangae-scaffold/sitepackages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/Users/USER/Documents/djangae-scaffold/sitepackages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/Users/USER/Documents/djangae-scaffold/sitepackages/django/db/migrations/executor.py", line 102, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/Users/USER/Documents/djangae-scaffold/sitepackages/django/db/migrations/migration.py", line 108, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/Users/USER/Documents/djangae-scaffold/sitepackages/django/db/migrations/operations/fields.py", line 37, in database_forwards
    field,
  File "/Users/USER/Documents/djangae-scaffold/sitepackages/django/db/backends/schema.py", line 374, in add_field
    definition, params = self.column_sql(model, field, include_default=True)
TypeError: column_sql() got an unexpected keyword argument 'include_default'
```

**Comment by adamalton** [comment]
The short answer is that migrations aren't really relevant to the App Engine Datastore because it's schemaless.  So the idea of adding a table or a column is kind of irrelevant.

My advice would be to just remove the `migrations` folder from your app, as it shouldn't really be needed.

The long answer is on its way in the form of documentation...

**Comment by yfr** [comment]
Thanks! I thought something like this would come up. 

But I still need to define the models, right?

**Comment by adamalton** [comment]
Yeah, you still need to define the model classes, you just don't need to define or run any migrations for them.

**Comment by yfr** [comment]
Thanks! Just figured it out myself. 

Would really help noobs like me if this where in the install/first-steps docs of djangae. (Any way to help you out with this?)

Anyway, thanks for the effort!

**Comment by adamalton** [comment]
I've now added some more info about migrations to the docs: http://djangae.readthedocs.org/en/latest/db_backend/#migrations

**Comment by yfr** [comment]
:+1: Thanks!
