### ISSUE TITLE
CloudStorage has no attribute rsplit

### ISSUE THREAD

**Issue by Stealthii** [potatolondon/djangae#577]
There are issues when using CloudStorage to push files (in this case, specifically images) from the admin panel. This is using latest Djangae at head this morning (b98cb70)

Relevant `settings_live.py` lines:
```python
from djangae.storage import CloudStorage
DEFAULT_FILE_STORAGE = CloudStorage(google_acl='public-read')
```

Traceback:
```pytb
Internal Server Error: /admin/redacted/contact/9/ (/base/data/home/apps/s~redacted-dev/1.390553172522402276/sitepackages/django/core/handlers/base.py:256)
Traceback (most recent call last):
  File "/base/data/home/apps/s~redacted-dev/1.390553172522402276/sitepackages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/base/data/home/apps/s~redacted-dev/1.390553172522402276/sitepackages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/base/data/home/apps/s~redacted-dev/1.390553172522402276/sitepackages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/base/data/home/apps/s~redacted-dev/1.390553172522402276/sitepackages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/base/data/home/apps/s~redacted-dev/1.390553172522402276/sitepackages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/base/data/home/apps/s~redacted-dev/1.390553172522402276/sitepackages/django/contrib/admin/options.py", line 1519, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/base/data/home/apps/s~redacted-dev/1.390553172522402276/sitepackages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/base/data/home/apps/s~redacted-dev/1.390553172522402276/sitepackages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/base/data/home/apps/s~redacted-dev/1.390553172522402276/sitepackages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/base/data/home/apps/s~redacted-dev/1.390553172522402276/sitepackages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/base/data/home/apps/s~redacted-dev/1.390553172522402276/sitepackages/django/contrib/admin/options.py", line 1467, in changeform_view
    self.save_model(request, new_object, form, not add)
  File "/base/data/home/apps/s~redacted-dev/1.390553172522402276/sitepackages/django/contrib/admin/options.py", line 1078, in save_model
    obj.save()
  File "/base/data/home/apps/s~redacted-dev/1.390553172522402276/sitepackages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/base/data/home/apps/s~redacted-dev/1.390553172522402276/sitepackages/django/db/models/base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/base/data/home/apps/s~redacted-dev/1.390553172522402276/sitepackages/django/db/models/base.py", line 800, in _save_table
    for f in non_pks]
  File "/base/data/home/apps/s~redacted-dev/1.390553172522402276/sitepackages/django/db/models/fields/files.py", line 315, in pre_save
    file.save(file.name, file, save=False)
  File "/base/data/home/apps/s~redacted-dev/1.390553172522402276/sitepackages/django/db/models/fields/files.py", line 90, in save
    name = self.field.generate_filename(self.instance, name)
  File "/base/data/home/apps/s~redacted-dev/1.390553172522402276/sitepackages/django/db/models/fields/files.py", line 329, in generate_filename
    return os.path.join(self.get_directory_name(), self.get_filename(filename))
  File "/base/data/home/apps/s~redacted-dev/1.390553172522402276/sitepackages/django/db/models/fields/files.py", line 326, in get_filename
    return os.path.normpath(self.storage.get_valid_name(os.path.basename(filename)))
  File "/base/data/home/apps/s~redacted-dev/1.390553172522402276/sitepackages/django/utils/functional.py", line 226, in inner
    self._setup()
  File "/base/data/home/apps/s~redacted-dev/1.390553172522402276/sitepackages/django/core/files/storage.py", line 334, in _setup
    self._wrapped = get_storage_class()()
  File "/base/data/home/apps/s~redacted-dev/1.390553172522402276/sitepackages/django/core/files/storage.py", line 329, in get_storage_class
    return import_string(import_path or settings.DEFAULT_FILE_STORAGE)
  File "/base/data/home/apps/s~redacted-dev/1.390553172522402276/sitepackages/django/utils/module_loading.py", line 21, in import_string
    module_path, class_name = dotted_path.rsplit('.', 1)
AttributeError: 'CloudStorage' object has no attribute 'rsplit'
```

**Comment by Stealthii** [comment]
Closing this as it was an incorrect definition, and raising a separate issue on CloudStorage issues.
