### ISSUE TITLE
Random test failure

### ISSUE THREAD

**Issue by Kazade** [potatolondon/djangae#618]
```======================================================================

ERROR: test_inherited_multiple_objects_returned_exception (model_inheritance.tests.ModelInheritanceDataTests)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/potatolondon/djangae/testapp/libs/django-stable-1.9.x/tests/model_inheritance/tests.py", line 231, in test_inherited_multiple_objects_returned_exception

    Restaurant.objects.get, id__lt=12321

  File "/opt/python/2.7.9/lib/python2.7/unittest/case.py", line 473, in assertRaises

    callableObj(*args, **kwargs)

  File "/home/travis/build/potatolondon/djangae/testapp/libs/django/db/models/manager.py", line 122, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

  File "/home/travis/build/potatolondon/djangae/testapp/libs/django/db/models/query.py", line 387, in get

    self.model._meta.object_name

DoesNotExist: Restaurant matching query does not exist.```

This only happens sometimes - but it's very annoying and might indicate a subtle error in the querying code.

**Comment by adamalton** [comment]
I think this is because the test does

```python
self.assertRaises(
            Place.MultipleObjectsReturned,
            Restaurant.objects.get, id__lt=12321
        )
```

The test doesn't appear to use any fixtures and in the `setUp` method it creates one restaurant with an unspecified PK, so my guess is that the reason it does `id__lt=12321` is just because the person who wrote the test thought that they needed to pass at least one filter to `.get()` or because `.get()` used to require at least one filter in the past.

The `12321` is almost definitely random and I'm pretty sure it could be removed.  We should submit a PR to Django and skip this test for now.

**Comment by adamalton** [comment]
https://github.com/django/django/pull/6291

**Comment by olasitarska** [comment]
That's merged in Django now.

**Comment by adamalton** [comment]
Yes, although it's only in Django master, so won't be in there until 1.9.x or 1.10.  Maybe we should conditionally skip that test if `django <= 1.9`?
