### ISSUE TITLE
Gauth backend raises IntegrityError when creating a new user

### ISSUE THREAD

**Issue by davidwtbuxton** [potatolondon/djangae#624]
A user is reporting errors when using Google Auth and Djangae's gauth backend, but only some of the time. Looks like it might be a race condition with 2 requests coming in very close together.

In their settings file, `DJANGAE_ALLOW_USER_PRE_CREATION=True` and other auth-related settings are not set.

Using Djangae commit 5b9bdd77d012293519d5df23c7d2022b39c44ac3

```
Internal Server Error: /
Traceback (most recent call last):
  File "/base/data/home/apps/s~myproj.12345/third_party/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/base/data/home/apps/s~myproj.12345/third_party/djangae/contrib/gauth/middleware.py", line 25, in process_request
    django_user = authenticate(google_user=google_user) or AnonymousUser()
  File "/base/data/home/apps/s~myproj.12345/third_party/django/contrib/auth/__init__.py", line 74, in authenticate
    user = backend.authenticate(**credentials)
  File "/base/data/home/apps/s~myproj.12345/third_party/djangae/contrib/gauth/common/backends.py", line 69, in authenticate
    return User.objects.create_user(user_id, email)
  File "/base/data/home/apps/s~myproj.12345/third_party/django/contrib/auth/models.py", line 187, in create_user
    **extra_fields)
  File "/base/data/home/apps/s~myproj.12345/third_party/django/contrib/auth/models.py", line 182, in _create_user
    user.save(using=self._db)
  File "/base/data/home/apps/s~myproj.12345/third_party/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/base/data/home/apps/s~myproj.12345/third_party/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/base/data/home/apps/s~myproj.12345/third_party/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/base/data/home/apps/s~myproj.12345/third_party/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/base/data/home/apps/s~myproj.12345/third_party/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/base/data/home/apps/s~myproj.12345/third_party/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/base/data/home/apps/s~myproj.12345/third_party/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/base/data/home/apps/s~myproj.12345/third_party/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/base/data/home/apps/s~myproj.12345/third_party/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/base/data/home/apps/s~myproj.12345/third_party/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/base/data/home/apps/s~myproj.12345/third_party/djangae/db/backends/appengine/base.py", line 102, in execute
    self.returned_ids = sql.execute()
  File "/base/data/home/apps/s~myproj.12345/third_party/djangae/db/backends/appengine/commands.py", line 935, in execute
    markers = constraints.acquire_bulk(self.model, self.entities)
  File "/base/data/home/apps/s~myproj.12345/third_party/djangae/db/constraints.py", line 133, in acquire_bulk
    markers.append(acquire(model, entity))
  File "/base/data/home/apps/s~myproj.12345/third_party/djangae/db/constraints.py", line 149, in acquire
    return acquire_identifiers(identifiers, entity.key())
  File "/base/data/home/apps/s~myproj.12345/third_party/djangae/db/constraints.py", line 90, in acquire_identifiers
    markers.append(acquire_marker(identifier))
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2732, in inner_wrapper
    return RunInTransactionOptions(options, func, *args, **kwds)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2630, in RunInTransactionOptions
    ok, result = _DoOneTry(function, args, kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2650, in _DoOneTry
    result = function(*args, **kwargs)
  File "/base/data/home/apps/s~myproj.12345/third_party/djangae/db/constraints.py", line 74, in acquire_marker
    raise IntegrityError("Unique constraint violation for kind {} on fields: {}".format(table_name, ", ".join(fields)))
IntegrityError: Unique constraint violation for kind authentication_user on fields: email
```

**Comment by Kazade** [comment]
@adamalton can we close this now?
