### ISSUE TITLE
Compatiblity with nose-django error 500

### ISSUE THREAD

**Issue by briva** [potatolondon/djangae#633]
I'm currently trying to setting up django-nose in my project.

I also use Djangae (https://djangae.readthedocs.org/en/latest/) for my app engin compatibility.

I add 'django_nose' in my INSTALLED_APPS I set TEST_RUNNER = 'django_nose.NoseTestSuiteRunner'

Launching "python manage.py test" is not raising any exception.

But when I want to launch the server with "python manage.py runserver", the server is running but when I try to call "localhost:8000" I get :

```
    ERROR    2016-03-23 15:59:49,299 wsgi.py:263]
Traceback (most recent call last):
  File "/Users/briva/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Users/briva/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Users/briva/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 96, in LoadObject
    __import__(cumulative_path)
  File "/Users/briva/Desktop/dangoptest/dangoptest/wsgi.py", line 18, in <module>
    application = DjangaeApplication(get_wsgi_application())
  File "/Users/briva/Desktop/dangoptest/lib/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup()
  File "/Users/briva/Desktop/dangoptest/lib/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/briva/Desktop/dangoptest/lib/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/briva/Desktop/dangoptest/lib/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "lib/django_nose/__init__.py", line 5, in <module>
    from django_nose.runner import BasicNoseRunner, NoseTestSuiteRunner
  File "lib/django_nose/runner.py", line 61, in <module>
    from django.test.simple import DjangoTestSuiteRunner as DiscoverRunner
ImportError: No module named simple
```

Thanks for answers.

**Comment by adamalton** [comment]
My guess is that you've got nose in your INSTALLED_APPS unconditionally
(i.e. it's always there, even if you're not running the tests), and that
it's installed in some kind of virtualenv or somewhere that is excluded
from the App Engine sandbox.

Try installing it into the sitepackages in the project folder, or even
better, only put it in INSTALLED_APPS when you need it.  You can do

if "test" in sys.argv:
    INSTALLED_APPS += ("django_nose",)

Adam

**Comment by briva** [comment]
It works. Thanks :)
