### ISSUE TITLE
Error when using cloudstorage

### ISSUE THREAD

**Issue by HonnKing** [potatolondon/djangae#642]
I don't know if this is a bug or if I have just missed some setup (the latter seems probable), but I am unable to get the cloudstorage to work. I tried the example from the [storage backend page](https://djangae.readthedocs.org/en/latest/storage/#cloud-storage) but I get an error:

````
Traceback (most recent call last):
  File "/Users/erikhonn/site/sitepackages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/Users/erikhonn/site/sitepackages/django/core/management/commands/runserver.py", line 107, in inner_run
    autoreload.raise_last_exception()
  File "/Users/erikhonn/site/sitepackages/django/utils/autoreload.py", line 252, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/erikhonn/site/sitepackages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/Users/erikhonn/site/sitepackages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/erikhonn/site/sitepackages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/erikhonn/site/sitepackages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/erikhonn/site/apps/defold/models.py", line 28, in <module>
    public_storage = storage.CloudStorage(google_acl='public-read')
  File "/Users/erikhonn/site/sitepackages/djangae/storage.py", line 285, in __init__
    if cloudstorage.common.local_run() and not cloudstorage.common.get_access_token():
NameError: global name 'cloudstorage' is not defined
````

I've looked through the documentation for how to use the Cloudstorage, but the Storage backends page is really all I can find.

**Comment by davidwtbuxton** [comment]
Hi,

Have you installed the [GoogleAppEngineCloudStorageClient][1], and checked it can be imported in your project?

David B.

[1]: https://pypi.python.org/pypi/GoogleAppEngineCloudStorageClient

**Comment by HonnKing** [comment]
I had not, that (and then Pillow) solved the issue. Thanks!

There probably should be some note about that in the docs. As someone who has very little GAE experience it's not very obvious that this dependency exists.

**Comment by adamalton** [comment]
Looks like you need to install the Cloud Storage library first:
https://cloud.google.com/appengine/docs/python/googlecloudstorageclient/using-cloud-storage#downloading_the_client_library

You should be able to be able to just add

GoogleAppEngineCloudStorageClient


to the requirements.txt file and re-run ./install_deps

Adam

**Comment by olasitarska** [comment]
Please reopen if still an issue.
