### ISSUE TITLE
Django version configuration falls over when using an alpha version

### ISSUE THREAD

**Issue by nealedj** [potatolondon/djangae#687]
To recreate, run djangae with an alpha version of Django, run the server, and make a request to it.

```
Traceback (most recent call last):
  File "../djangae/testapp/libs/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "../djangae/testapp/libs/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "../djangae/testapp/libs/google_appengine/google/appengine/runtime/wsgi.py", line 96, in LoadObject
    __import__(cumulative_path)
  File "../djangae/testapp/testapp/wsgi.py", line 16, in <module>
    from django.core.wsgi import get_wsgi_application
  File "../djangae/testapp/libs/django/__init__.py", line 5, in <module>
    __version__ = get_version(VERSION)
  File "../djangae/testapp/libs/django/utils/version.py", line 23, in get_version
    git_changeset = get_git_changeset()
  File "../djangae/testapp/libs/django/utils/lru_cache.py", line 125, in wrapper
    result = user_function(*args, **kwds)
  File "../djangae/testapp/libs/django/utils/version.py", line 72, in get_git_changeset
    git_log = subprocess.Popen('git log --pretty=format:%ct --quiet -1 HEAD',
AttributeError: 'module' object has no attribute 'Popen'
```

`django.utils.get_version()` is called from `django/__init__.py` which will get the commit hash from git if the version contains "alpha".

**Comment by olasitarska** [comment]
Fixed by @chargrizzle 💥
