### ISSUE TITLE
How to disable djangae tests ?

### ISSUE THREAD

**Issue by briva** [potatolondon/djangae#698]
Hello.

I would like to launch tests that I wrote for my application.

I setup django-nose like that : 

INSTALLED_APPS += ("django_nose",)
TEST_RUNNER = 'django_nose.NoseTestSuiteRunner'
NOSE_ARGS = [
        '--cover-package=games,groups',
        '--with-coverage',
    ]

But when i launch my test by this way : ./manage.py test

djangae tests is also launched : 

tiny part of the traceback :

> ======================================================================
ERROR: test_newly_created_objects_returned (djangae.contrib.consistency.tests.ConsistencyTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "lib/djangae/contrib/consistency/tests.py", line 34, in test_newly_created_objects_returned
    existing = TestModel.objects.create(name='existing')
  File "lib/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "lib/django/db/models/query.py", line 401, in create
    obj.save(force_insert=True, using=self.db)
  File "lib/django/db/models/base.py", line 708, in save
    force_update=force_update, update_fields=update_fields)
  File "lib/django/db/models/base.py", line 736, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "lib/django/db/models/base.py", line 820, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "lib/django/db/models/base.py", line 859, in _do_insert
    using=using, raw=raw)
  File "lib/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "lib/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "lib/django/db/models/sql/compiler.py", line 1060, in execute_sql
    cursor.execute(sql, params)
  File "lib/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "lib/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "lib/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "lib/django/db/backends/mysql/base.py", line 112, in execute
    return self.cursor.execute(query, args)
  File "lib/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "lib/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table 'test_owls_be.djangae_testmodel' doesn't exist")

**Comment by moggers87** [comment]
I don't know much about nose, but I think you need to tell it which applications to run tests on. Does the default test runner work?
