### ISSUE TITLE
Pb after install gcloud (_find_sdk_from_path())

### ISSUE THREAD

**Issue by briva** [potatolondon/djangae#700]
Hello,

I install gloud and I got a problem.

Launching my app by the GoogleAppEngineLauncher (MacOS) is working.

But when I do a "python manage.py runserver" in cli i get that :

> Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "lib/djangae/core/management/__init__.py", line 65, in execute_from_command_line
    return _execute_from_command_line(namespace.sandbox, ['manage.py'] + namespace.args, **overrides)
  File "lib/djangae/core/management/__init__.py", line 42, in _execute_from_command_line
    **sandbox_overrides
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "lib/djangae/sandbox.py", line 299, in activate
    sys.path[0:0] = [_find_sdk_from_path()]
  File "lib/djangae/sandbox.py", line 58, in _find_sdk_from_path
    'The Cloud SDK is on the path, but the app engine SDK dir could not be found'
RuntimeError: The Cloud SDK is on the path, but the app engine SDK dir could not be found

Before installing glcoud, everything worked well.

**Comment by adamalton** [comment]
It looks like either:

* The App Engine component of the Cloud SDK is not installed, see: https://cloud.google.com/sdk/docs/managing-components.
* Or Google have moved the location of the App Engine SDK inside the Cloud SDK.

I would suggest putting PDB into djangae/sandbox.py in `_find_sdk_from_path` and just step through and see what's what.

**Comment by olasitarska** [comment]
Please reopen if this is still an issue :)
