### ISSUE TITLE
Issue arround subprocess.CalledProcessError

### ISSUE THREAD

**Issue by yanikkoval** [potatolondon/djangae#706]
After fixing this issue https://github.com/potatolondon/djangae/issues/539 by exporting variable I run into another one: 
```
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/djangae/core/management/__init__.py", line 65, in execute_from_command_line
    return _execute_from_command_line(namespace.sandbox, ['manage.py'] + namespace.args, **overrides)
  File "/usr/local/lib/python2.7/dist-packages/djangae/core/management/__init__.py", line 42, in _execute_from_command_line
    **sandbox_overrides
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/djangae/sandbox.py", line 299, in activate
    sys.path[0:0] = [_find_sdk_from_path()]
  File "/usr/local/lib/python2.7/dist-packages/djangae/sandbox.py", line 50, in _find_sdk_from_path
    path = subprocess.check_output([which, _SCRIPT_NAME]).strip()
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['which', 'dev_appserver.py']' returned non-zero exit status 1
```

Appears after running `python manage.py runserver`. Maybe someone had a similar issue?

**Comment by yanik5** [comment]
Oops, looks like I missing some libs. Will send fix soon for incoming searches :)
