### ISSUE TITLE
`./manage.py runserver` fails with Djangae 0.9.7 and Django 1.10

### ISSUE THREAD

**Issue by davidwtbuxton** [potatolondon/djangae#749]
Hi,

I get an AttributeError exception when trying to start the development server with Djangae 0.9.7 and Django 1.10 (both installed from PyPI).

```
$ ./manage.py runserver
INFO     2016-08-28 13:31:58,757 blobstore_service.py:73] Starting blobstore service on localhost:8080
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/jeff/example/libs/djangae/core/management/__init__.py", line 65, in execute_from_command_line
    return _execute_from_command_line(namespace.sandbox, ['manage.py'] + namespace.args, **overrides)
  File "/Users/jeff/example/libs/djangae/core/management/__init__.py", line 45, in _execute_from_command_line
    return django_management.execute_from_command_line(argv)
  File "/Users/jeff/example/libs/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/jeff/example/libs/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/jeff/example/libs/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/jeff/example/libs/django/core/management/__init__.py", line 41, in load_command_class
    return module.Command()
  File "/Users/jeff/example/libs/djangae/management/commands/runserver.py", line 105, in __new__
    instance.option_list += (
AttributeError: 'Command' object has no attribute 'option_list'
```

The same command works if I install Djangae 0.9.7 and Django 1.9.9.

It looks like `BaseCommand.option_list` [was removed in Django 1.10][1] as part of [ticket 19973][2]

[1]: https://github.com/django/django/commit/6a70cb53971a19f2d9e71d5ee24bfb0e844b4d9d
[2]: https://code.djangoproject.com/ticket/19973

**Comment by mirzadelic** [comment]
Same error.. Please merge PR.
