### ISSUE TITLE
AttributeError: 'SelectCommand' object has no attribute 'query'

### ISSUE THREAD

**Issue by Ali-aqrabawi** [potatolondon/djangae#775]
i have an appengine app that store patients data in datastore , login is working fine , 
however when i request to return patients data i get , below exception 

here is the code : 
https://github.com/Ali-aqrabawi/ezclinic

here is the excpetion  : 

13:55:51.945
Internal Server Error: /
13:55:51.945
Traceback (most recent call last):
13:55:51.945
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/django/core/handlers/exception.py", line 39, in inner
13:55:51.945
    response = get_response(request)
13:55:51.945
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/django/core/handlers/base.py", line 249, in _legacy_get_response
13:55:51.945
    response = self._get_response(request)
13:55:51.945
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/django/core/handlers/base.py", line 187, in _get_response
13:55:51.945
    response = self.process_exception_by_middleware(e, request)
13:55:51.945
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/django/core/handlers/base.py", line 185, in _get_response
13:55:51.945
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
13:55:51.945
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/simple_forms/apps/core/views.py", line 68, in home
13:55:51.945
    return render(request, 'core/home.html', {'persons': persons})
13:55:51.945
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/django/shortcuts.py", line 30, in render
13:55:51.945
    content = loader.render_to_string(template_name, context, request, using=using)
13:55:51.945
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/django/template/loader.py", line 68, in render_to_string
13:55:51.946
    return template.render(context, request)
13:55:51.946
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/django/template/backends/django.py", line 66, in render
13:55:51.946
    return self.template.render(context)
13:55:51.946
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/django/template/base.py", line 208, in render
13:55:51.946
    return self._render(context)
13:55:51.946
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/django/template/base.py", line 199, in _render
13:55:51.946
    return self.nodelist.render(context)
13:55:51.946
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/django/template/base.py", line 994, in render
13:55:51.946
    bit = node.render_annotated(context)
13:55:51.946
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/django/template/base.py", line 961, in render_annotated
13:55:51.946
    return self.render(context)
13:55:51.946
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/django/template/loader_tags.py", line 174, in render
13:55:51.946
    return compiled_parent._render(context)
13:55:51.946
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/django/template/base.py", line 199, in _render
13:55:51.946
    return self.nodelist.render(context)
13:55:51.947
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/django/template/base.py", line 994, in render
13:55:51.947
    bit = node.render_annotated(context)
13:55:51.947
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/django/template/base.py", line 961, in render_annotated
13:55:51.947
    return self.render(context)
13:55:51.947
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/django/template/loader_tags.py", line 70, in render
13:55:51.947
    result = block.nodelist.render(context)
13:55:51.947
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/django/template/base.py", line 994, in render
13:55:51.947
    bit = node.render_annotated(context)
13:55:51.947
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/django/template/base.py", line 961, in render_annotated
13:55:51.947
    return self.render(context)
13:55:51.947
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/django/template/defaulttags.py", line 166, in render
13:55:51.947
    len_values = len(values)
13:55:51.947
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/django/core/paginator.py", line 112, in __len__
13:55:51.947
    return len(self.object_list)
13:55:51.948
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/django/db/models/query.py", line 238, in __len__
13:55:51.948
    self._fetch_all()
13:55:51.948
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/django/db/models/query.py", line 1087, in _fetch_all
13:55:51.948
    self._result_cache = list(self.iterator())
13:55:51.948
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/django/db/models/query.py", line 54, in __iter__
13:55:51.948
    results = compiler.execute_sql()
13:55:51.956
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/django/db/models/sql/compiler.py", line 824, in execute_sql
13:55:51.956
    sql, params = self.as_sql()
13:55:51.956
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/djangae/db/backends/appengine/compiler.py", line 45, in as_sql
13:55:51.956
    self.query
13:55:51.956
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/djangae/db/backends/appengine/commands.py", line 391, in __init__
13:55:51.956
    self.query = transform_query(connection, query)
13:55:51.957
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/djangae/db/backends/appengine/query.py", line 678, in transform_query
13:55:51.957
    return _get_parser(query, connection).get_transformed_query()
13:55:51.957
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/djangae/db/backends/appengine/parsers/base.py", line 336, in get_transformed_query
13:55:51.957
    output = self._generate_where_node()
13:55:51.957
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/djangae/db/backends/appengine/parsers/base.py", line 309, in _generate_where_node
13:55:51.957
    compiler=self.django_query.get_compiler(self.connection.alias)
13:55:51.957
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/djangae/db/backends/appengine/parsers/base.py", line 79, in _walk_django_where
13:55:51.957
    walk_node(query.where, **kwargs)
13:55:51.957
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/djangae/db/backends/appengine/parsers/base.py", line 69, in walk_node
13:55:51.957
    leaf_callback(child, **new_kwargs)
13:55:51.957
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/djangae/db/backends/appengine/parsers/base.py", line 202, in _where_node_leaf_callback
13:55:51.957
    raise NotSupportedError("Attempted probable subquery, these aren't supported on the datastore")
13:55:51.957
NotSupportedError: Attempted probable subquery, these aren't supported on the datastore
13:55:52.358
Unable to translate query to string (/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/djangae/db/backends/appengine/commands.py:749)
Traceback (most recent call last):
  File "/base/data/home/apps/s~ezclinic16/1.397025003384468622/lib/djangae/db/backends/appengine/commands.py", line 729, in __unicode__
    qry = json.loads(self.query.serialize())
AttributeError: 'SelectCommand' object has no attribute 'query'

**Comment by adamalton** [comment]
What's the actual query which is causing that?

**Comment by Ali-aqrabawi** [comment]
i believe its somewhere here : 

def home(request):
    if not request.user.is_authenticated():
        return render(request, 'core/login.html')
    else:
        persons = Person.objects.filter(user=request.user)
        page = request.GET.get('page', 1)
        paginator = Paginator(persons, 2)

        try:
            persons = paginator.page(page)
        except PageNotAnInteger:
            persons= paginator.page(1)
        except EmptyPage:
            persons = paginator.page(paginator.num_pages)


    return render(request, 'core/home.html', {'persons': persons})

**Comment by grzes** [comment]
This view doesn't do anything out of the ordinary, I checked out your code and you're using django1.10 and an "old" djangae version from before we included 1.10 support. Try using the latest djangae, or django1.9.

**Comment by grzes** [comment]
The above commit fixes a similar issue. Hmm... I couldn't actually reproduce your problem. Please update djangae to the latest release and reopen if you're still experiencing this.
