### ISSUE TITLE
TypeError running `./manage.py runserver` with SDK 1.9.49

### ISSUE THREAD

**Issue by davidwtbuxton** [potatolondon/djangae#797]
Hi,

I'm testing the new App Engine SDK with my project. Running the development server with Djangae works fine with SDK 1.9.40, but the same command after switching to SDK 1.9.49 fails with a TypeError.

Traceback:

```
$ ./manage.py runserver
Traceback (most recent call last):
  File "./manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/my-project/sitepackages/prod/djangae/core/management/__init__.py", line 65, in execute_from_command_line
    return _execute_from_command_line(namespace.sandbox, ['manage.py'] + namespace.args, **overrides)
  File "/my-project/sitepackages/prod/djangae/core/management/__init__.py", line 42, in _execute_from_command_line
    **sandbox_overrides
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/my-project/sitepackages/prod/djangae/sandbox.py", line 398, in activate
    with SANDBOXES[sandbox_name](**kwargs):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/my-project/sitepackages/prod/djangae/sandbox.py", line 158, in _local
    dispatcher = _create_dispatcher(configuration, options)
  File "/my-project/sitepackages/prod/djangae/sandbox.py", line 106, in _create_dispatcher
    _create_dispatcher.singleton = dispatcher.Dispatcher(*dispatcher_args)
TypeError: __init__() takes exactly 18 arguments (16 given)
```

Not certain, but I think this is because [Djangae is skipping passing 2 extra arguments to the dispatcher][1], because the new SDK fails a version check.

This is the contents of `VERSION` in the new SDK:

```
$ cat 1.9.49/google_appengine/VERSION 
release: "0.0.0"
timestamp: 0
api_versions: ['1']
supported_api_versions:
  python:
    api_versions: ['1']
  python27:
    api_versions: ['1']
  go:
    api_versions: ['go1']
  java7:
    api_versions: ['1.0']
```

This project is using Django 1.8.15, Djangae 0.9.8.

[1]: https://github.com/potatolondon/djangae/blob/v0.9.8/djangae/sandbox.py#L98

**Comment by moggers87** [comment]
How old is 1.9.19? I'd be tempted to remove this code and require more recent SDK versions.

**Comment by davidwtbuxton** [comment]
I made a patch to remove all version checks, so it would only work with 1.9.22 or later. Now when running `./manage.py runserver` under SDK 1.9.49 I see this error:

```
$ ./manage.py runserver
INFO     2016-12-14 09:21:33,728 blobstore_service.py:75] Starting blobstore service on localhost:8080
Validating models...

System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DEBUG.

System check identified 1 issue (0 silenced).
December 14, 2016 - 09:21:34
Django version 1.8.17.dev20161214083637, using settings 'testapp.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

INFO     2016-12-14 09:21:34,258 devappserver2.py:764] Skipping SDK update check.
INFO     2016-12-14 09:21:34,263 api_server.py:268] Starting API server at: http://127.0.0.1:8002
INFO     2016-12-14 09:21:34,269 dispatcher.py:199] Starting module "default" running at: http://localhost:8000
INFO     2016-12-14 09:21:34,271 admin_server.py:116] Starting admin server at: http://127.0.0.1:8001
Exception in thread Mtime File Watcher:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/david/.sdk/1.9.49/google_appengine/google/appengine/tools/devappserver2/mtime_file_watcher.py", line 47, in _refresh
    self._filename_to_mtime = self._generate_filename_to_mtime()
  File "/Users/david/.sdk/1.9.49/google_appengine/google/appengine/tools/devappserver2/mtime_file_watcher.py", line 147, in _generate_filename_to_mtime
    watcher_common.skip_ignored_dirs(dirpath, dirnames, self._skip_files_re)
TypeError: skip_ignored_dirs() takes exactly 1 argument (3 given)

Exception in thread Instance Adjustment:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/david/.sdk/1.9.49/google_appengine/google/appengine/tools/devappserver2/module.py", line 1504, in _loop_adjusting_instances
    self._handle_changes(_CHANGE_POLLING_MS)
  File "/Users/david/.sdk/1.9.49/google_appengine/google/appengine/tools/devappserver2/module.py", line 411, in _handle_changes
    file_changes = self._watcher.changes(timeout)
  File "/Users/david/.sdk/1.9.49/google_appengine/google/appengine/tools/devappserver2/mtime_file_watcher.py", line 89, in changes
    self._refresh()
  File "/Users/david/.sdk/1.9.49/google_appengine/google/appengine/tools/devappserver2/mtime_file_watcher.py", line 47, in _refresh
    self._filename_to_mtime = self._generate_filename_to_mtime()
  File "/Users/david/.sdk/1.9.49/google_appengine/google/appengine/tools/devappserver2/mtime_file_watcher.py", line 147, in _generate_filename_to_mtime
    watcher_common.skip_ignored_dirs(dirpath, dirnames, self._skip_files_re)
TypeError: skip_ignored_dirs() takes exactly 1 argument (3 given)

```

**Comment by adamalton** [comment]
I seem to remember that we've got a monkey patch for something in that skip dirs stuff.

**Comment by farridav** [comment]
+1 I'm also using the new SDK and hitting similar issues, would it make sense to open an issue and accompanying pull request for new SDK support, then integration issues can be resolved as they are found..

This is also a relatively new issue, as I've been happily (sort of) using gcloud within my Djangae project until today when I did `gcloud components update`

**Comment by farridav** [comment]
Just in case its of interest, I have this working using the [following patch](https://github.com/potatolondon/djangae/compare/master...farridav:farridav/sdk_patches.patch) diff here https://github.com/potatolondon/djangae/compare/master...farridav:farridav/sdk_patches

**Comment by davidwtbuxton** [comment]
There's also a version check in djangae/management/commands/runserver.py

https://github.com/davidwtbuxton/djangae/commit/fbed6ac73a39c6fef7b86868d686a00f91fe9279

**Comment by farridav** [comment]
Good spot, Ive added that to my fork also (as im maintaining backwards compatibility in it)

**Comment by davidwtbuxton** [comment]
@farridav 


https://github.com/farridav/djangae/commit/7dae72dacf03f0b11dbc5c48ba881f1b21ffb9b4

```
def skip_ignored_dirs(dirpath, dirs, skip_files_re=None):
    """ Replacement for devappserver2.watchter_common.skip_ignored_dirs
    - to be monkeypatched into place.
    """
    # Note that this function modifies the `dirs` list in place, it doesn't return anything.
    # Also note that `dirs` is a list of dir *names* not dir *paths*, which means that we can't
    # differentiate between /foo/bar and /moo/bar because we just get 'bar'. But allowing that
    # would require a whole load more monkey patching.
    from google.appengine.tools.devappserver2 import watcher_common
    watcher_common._remove_pred(dirs, lambda d: d.startswith(watcher_common._IGNORED_PREFIX))
    watcher_common._remove_pred(
        dirs,
        lambda d: any(regex.search(d) for regex in DJANGAE_RUNSERVER_IGNORED_DIR_REGEXES)
    )
```

Won't this break when used on SDK versions before 1.9.49?

**Comment by farridav** [comment]
Ah yes @davidwtbuxton, as the first arguments are positional.. given that I'm already having to use my own fork of this project, I'm caring less and less about backwards compatibility 

I've also found more issues that I think are related..

I'm unable to pass `--app_id` or `-A` or `--application` through with manage.py commands :(

**Comment by farridav** [comment]
Started a thread [here](https://groups.google.com/forum/#!topic/djangae-users/1JQ7TlB_jrs) as its more frequently used than g/h issues for these sort of things

**Comment by moggers87** [comment]
[Upstream report](https://code.google.com/p/googleappengine/issues/detail?id=13439)

**Comment by yeelan0319** [comment]
@davidwtbuxton Thanks. This temporarily helped my problem.

**Comment by asendecka** [comment]
@farridav could you elaborate more about your issue with passing flags through `manage.py`? Isn't it a same issue as this one: #688?
