### ISSUE TITLE
Support deletion of objects which cause a NotSupportedError during collection

### ISSUE THREAD

**Issue by nealedj** [potatolondon/djangae#800]
Given the following model structure:

```
class Zoo(models.Model):
  ...

class Enclosure(models.Model):
  zoo = models.ForeignKey(Zoo)

class Animal(models.Model):
  enclosure = models.ForeignKey(Enclosure)
```

If a top-level object (`Zoo`) is deleted then all of the `Enclosure` and `Animal` objects will be deleted.

The deletion collector will execute a `SELECT ... FROM Enclosure WHERE zoo_id=x` query to get the `Enclosure` objects. However, it will then execute a `SELECT ... From Animal WHERE enclosure_id IN [all enclosure PKs]`. If there are more than 30 `Enclosure` objects then the following error will be raised:

```
Traceback (most recent call last):
  File "../django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "../django/contrib/admin/options.py", line 618, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "../django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "../django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "../django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "../django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "../django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "../django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "../django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "../django/contrib/admin/options.py", line 1709, in delete_view
    [obj], opts, request.user, self.admin_site, using)
  File "../django/contrib/admin/utils.py", line 118, in get_deleted_objects
    collector.collect(objs)
  File "../django/contrib/admin/utils.py", line 182, in collect
    return super(NestedObjects, self).collect(objs, source_attr=source_attr, **kwargs)
  File "../django/db/models/deletion.py", line 229, in collect
    field.rel.on_delete(self, field, sub_objs, self.using)
  File "../django/db/models/deletion.py", line 18, in CASCADE
    source_attr=field.name, nullable=field.null)
  File "../django/contrib/admin/utils.py", line 182, in collect
    return super(NestedObjects, self).collect(objs, source_attr=source_attr, **kwargs)
  File "../django/db/models/deletion.py", line 228, in collect
    elif sub_objs:
  File "../django/db/models/query.py", line 170, in __nonzero__
    return type(self).__bool__(self)
  File "../django/db/models/query.py", line 166, in __bool__
    self._fetch_all()
  File "../django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "../django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "../django/db/models/sql/compiler.py", line 829, in execute_sql
    sql, params = self.as_sql()
  File "../djangae/db/backends/appengine/compiler.py", line 45, in as_sql
    self.query
  File "../djangae/db/backends/appengine/commands.py", line 394, in __init__
    self.query = normalize_query(self.query)
  File "../djangae/db/backends/appengine/dnf.py", line 203, in normalize_query
    raise NotSupportedError("Unable to run query as it required more than 30 subqueries")
NotSupportedError: Unable to run query as it required more than 30 subqueries
```

Using a custom collector we might be able to batch these collection queries. Since that's unbounded we risk running into timeouts - but maybe that's an issue best handled by application logic?

**Comment by Kazade** [comment]
OK so there are a couple of approaches here...

1. Try to override the collector to do something datastore-friendly
2. Do something to the datastore connector to make these queries work

### Option 1

Normal programmatic model deletions just call the collector in their delete function (see `django/db/models/base.py:894`) so overriding this would be easy with a mixin. We could enforce the mixin using the system checks framework and write a check to detect user models with cascading foreign keys which show a warning. However... the Django admin ruins this plan because it uses it's own (poorly commented and named) collector called `NestedObjects` (see `django/contrib/admin/utils.py`) and overriding that isn't possible without monkey-patching something, and we do enough of that with content types. What we could do is propose a change to upstream to allow overriding the collector but that will be a long process and won't help people on 1.8 - 1.10

### Option 2

We could remove the 30 limit on IN queries which is entirely possible as MultiQuery is implemented entirely client-side by running 30 individual queries then zig-zag merge joining them. Obviously this would be incredibly slow and would use up a bunch of memory, but it would stop people hitting this limit all over the place. I started implementing a multi-threaded version of MultiQuery which might help things, but we should still at least log a warning on 50+ IN/OR branches and probably hard limit at 1000. We could also provide a way to enforce a strict limit to prevent slow queries.


I'll give this some more thought...

**Comment by Kazade** [comment]
Actually, disregard that!

Turns out that the collector uses `connection.ops.bulk_batch_size` to determine the batches to perform the collection, and it turns out we don't override this! By setting it to return 30, we should just solve the problem!

I'll write some tests tomorrow and send a PR if it works
