### ISSUE TITLE
Django Compressor precompiler breaks with monkey-patched subprocess module

### ISSUE THREAD

**Issue by nickdandakis** [potatolondon/djangae#852]
Trying to use SASS on a project set up with the djangae-scaffold, however I think this is an error with the djangae module. Using [Django Compressor](http://django-compressor.readthedocs.io/en/latest/) with the following configuration in my `settings.py`.

```python
COMPRESS_PRECOMPILERS = (
    # ('text/x-scss', 'django_libsass.SassCompiler'),
    ('text/x-scss', 'sass --scss {infile}'),
)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)
```

I get the following error.

```bash
Traceback (most recent call last):
  File "/Users/ndandakis/Workspace/redacted/sitepackages/prod/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ndandakis/Workspace/redacted/sitepackages/prod/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ndandakis/Workspace/redacted/fieldguide/views.py", line 6, in index
    return render(request, 'fieldguide/index.html')
  File "/Users/ndandakis/Workspace/redacted/sitepackages/prod/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Users/ndandakis/Workspace/redacted/sitepackages/prod/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/Users/ndandakis/Workspace/redacted/sitepackages/prod/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/Users/ndandakis/Workspace/redacted/sitepackages/prod/django/template/base.py", line 206, in render
    return self._render(context)
  File "/Users/ndandakis/Workspace/redacted/sitepackages/prod/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/Users/ndandakis/Workspace/redacted/sitepackages/prod/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/ndandakis/Workspace/redacted/sitepackages/prod/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/ndandakis/Workspace/redacted/sitepackages/prod/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/Users/ndandakis/Workspace/redacted/sitepackages/prod/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/Users/ndandakis/Workspace/redacted/sitepackages/prod/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/ndandakis/Workspace/redacted/sitepackages/prod/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/ndandakis/Workspace/redacted/sitepackages/prod/compressor/templatetags/compress.py", line 127, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/Users/ndandakis/Workspace/redacted/sitepackages/prod/compressor/templatetags/compress.py", line 103, in render_compressed
    rendered_output = compressor.output(mode, forced=forced)
  File "/Users/ndandakis/Workspace/redacted/sitepackages/prod/compressor/css.py", line 49, in output
    ret.append(subnode.output(*args, **kwargs))
  File "/Users/ndandakis/Workspace/redacted/sitepackages/prod/compressor/css.py", line 51, in output
    return super(CssCompressor, self).output(*args, **kwargs)
  File "/Users/ndandakis/Workspace/redacted/sitepackages/prod/compressor/base.py", line 292, in output
    output = '\n'.join(self.filter_input(forced))
  File "/Users/ndandakis/Workspace/redacted/sitepackages/prod/compressor/base.py", line 232, in filter_input
    for hunk in self.hunks(forced):
  File "/Users/ndandakis/Workspace/redacted/sitepackages/prod/compressor/base.py", line 204, in hunks
    precompiled, value = self.precompile(value, **options)
  File "/Users/ndandakis/Workspace/redacted/sitepackages/prod/compressor/base.py", line 264, in precompile
    charset=charset, command=filter_or_command, mimetype=mimetype)
  File "/Users/ndandakis/Workspace/redacted/sitepackages/prod/compressor/filters/base.py", line 217, in __init__
    super(CachedCompilerFilter, self).__init__(*args, **kwargs)
  File "/Users/ndandakis/Workspace/redacted/sitepackages/prod/compressor/filters/base.py", line 137, in __init__
    self.stdout = self.stdin = self.stderr = subprocess.PIPE
AttributeError: 'module' object has no attribute 'PIPE'
```

Printing out `subprocess.__file__` gives me `/Users/ndandakis/Workspace/redacted/sitepackages/dev/google_appengine/google/appengine/dist/subprocess.pyc`, which made me realize that some patching was going on.

I then found the following in `djangae/sandbox.py`

```python
def allow_modules(func, *args):
    """
        dev_appserver likes to kill your imports with meta_path madness so you
        use the internal ones instead of system ones, this wrapper reloads the
        modules and patches the google internal ones with the __dict__ from the
        system modules, this seems to be the cleanest way to do this even though
        it is a bit hacky
    """
    def _wrapped(*args, **kwargs):
        with allow_modules_context():
            return func(*args, **kwargs)
    return _wrapped
```

Is the subprocess module not being patched correctly? Am I configuring SASS incorrectly here?

**Comment by moggers87** [comment]
I'm not too familiar with Django Compressor, but having a quick look through the docs it seems like it's trying to call `sass` via subprocess during request/response time. Even if that could work locally somehow, it won't work once deployed. You might want to check the docs for offline compression: http://django-compressor.readthedocs.io/en/latest/usage/#offline-compression

**Comment by nickdandakis** [comment]
@moggers87, I should've mentioned that running compress as a standalone command works just fine. However, running it within the dev_appserver fails.

```
# this works fine
python manage.py compress --force

# this throws the error above
python manage.py runserver
```

**Comment by moggers87** [comment]
Right, which is to be expected.

`dev_appserver` has all the same restrictions that App Engine has - you can't call a script or another binary via `subprocess` (or any other means) inside the sandbox.

**Comment by nickdandakis** [comment]
I see. I expected the development server to allow for SASS compilation. Then I'd compile SASS for deployment. 

Thank you for the clarification @moggers87!
