### ISSUE TITLE
Calling `modules.get_hostname()` locally gives a KeyError

### ISSUE THREAD

**Issue by nealedj** [potatolondon/djangae#853]
```
from google.appengine.api import modules

modules.get_hostname()

...

  File ".../google_appengine/google/appengine/api/modules/modules.py", line 459, in get_hostname
    _ResultHook).get_result()
  File ".../google_appengine/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File ".../google_appengine/google/appengine/api/modules/modules.py", line 442, in _ResultHook
    _CheckAsyncResult(rpc, mapped_errors, [])
  File ".../google_appengine/google/appengine/api/modules/modules.py", line 139, in _CheckAsyncResult
    rpc.check_success()
  File ".../google_appengine/google/appengine/api/apiproxy_stub_map.py", line 579, in check_success
    self.__rpc.CheckSuccess()
  File ".../google_appengine/google/appengine/api/apiproxy_rpc.py", line 157, in _WaitImpl
    self.request, self.response)
  File ".../google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 204, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File ".../google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 267, in _MakeRealSyncCall
    raise pickle.loads(response_pb.exception())
RuntimeError: KeyError('mRMDWbtvop',)
```

I believe this is significant because a recent version of the SDK (currently 1.9.50) has started calling this method when creating tasks for the dev server. See `Task.__host_from_target()`.

Jobs created by the deferred library don't seem to be affected.

I can't get any MapReduce jobs to run because it creates tasks via the pipelines library.

See also #845 and https://github.com/potatolondon/search/issues/51

**Comment by nealedj** [comment]
It looks like this is down to different `WSGIRequestInfo` objects being used by the APIServer (hit by the modules.get_hostname() call) and the one that is used by the main dev server.

```
wsgi_request_info.py:87] start_request <google.appengine.tools.devappserver2.wsgi_request_info.WSGIRequestInfo object at 0x1100d3c90>
wsgi_request_info.py:166] get_version. <djangae.sandbox.CustomWSGIRequestInfo object at 0x10dd80c90>
wsgi_request_info.py:95] end_request. <google.appengine.tools.devappserver2.wsgi_request_info.WSGIRequestInfo object at 0x1100d3c90>
```

**Comment by nealedj** [comment]
Here's the traceback from the API server:

```
Traceback (most recent call last):
  File ".../google_appengine/google/appengine/tools/devappserver2/api_server.py", line 310, in _handle_POST
    api_response = _execute_request(request).Encode()
  File ".../google_appengine/google/appengine/tools/devappserver2/api_server.py", line 196, in _execute_request
    make_request()
  File ".../google_appengine/google/appengine/tools/devappserver2/api_server.py", line 191, in make_request
    request_id)
  File ".../google_appengine/google/appengine/api/apiproxy_stub.py", line 129, in MakeSyncCall
    method(request, response, request_id)
  File ".../google_appengine/google/appengine/api/modules/modules_stub.py", line 133, in _Dynamic_GetHostname
    request, request_id)
  File ".../google_appengine/google/appengine/api/modules/modules_stub.py", line 44, in _GetModuleAndVersionFromRequest
    module, dispatcher = self._GetModuleFromRequest(request, request_id)
  File ".../google_appengine/google/appengine/api/modules/modules_stub.py", line 40, in _GetModuleFromRequest
    module = self.request_data.get_module(request_id)
  File ".../google_appengine/google/appengine/tools/devappserver2/wsgi_request_info.py", line 154, in get_module
    return self._request_id_to_module_configuration[request_id].module_name
KeyError: 'mRMDWbtvop'
```

**Comment by robcharlwood** [comment]
I can confirm that I am also getting this issue. I back-traced the SDK to the last known good version working against the latest release of djangae - ``djangae==0.9.9``. I found that ``google-appengine-sdk==1.9.37`` is the latest version to work with ``djangae`` without raising the above errors. Anything more recent than that doesn't work.

**Comment by nealedj** [comment]
This gist patches the SDK to workaround this issue: https://gist.github.com/nealedj/5577b57be09e91bf03765550b85408e8
