### ISSUE TITLE
Djangae==0.9.9 introduces dependency on Pillow package

### ISSUE THREAD

**Issue by seawolf42** [potatolondon/djangae#906]
I have a project that does not use any storage and does not use any image fields. It works file with `djangae==0.9.8`, but when I try to test the same project using `djangae==0.9.9` I am receiving the following exception:

```
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/seawolf/repos/django-autometrics/.eggs/djangae-0.9.9-py2.7.egg/djangae/core/management/__init__.py", line 62, in execute_from_command_line
    return _execute_from_command_line(namespace.sandbox, ['manage.py'] + other_args, **overrides)
  File "/Users/seawolf/repos/django-autometrics/.eggs/djangae-0.9.9-py2.7.egg/djangae/core/management/__init__.py", line 45, in _execute_from_command_line
    return django_management.execute_from_command_line(argv)
  File "/Users/seawolf/repos/django-autometrics/.eggs/Django-1.8.18-py2.7.egg/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/seawolf/repos/django-autometrics/.eggs/Django-1.8.18-py2.7.egg/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/seawolf/repos/django-autometrics/.eggs/Django-1.8.18-py2.7.egg/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/Users/seawolf/repos/django-autometrics/.eggs/Django-1.8.18-py2.7.egg/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/seawolf/repos/django-autometrics/.eggs/Django-1.8.18-py2.7.egg/django/core/management/commands/test.py", line 74, in execute
    super(Command, self).execute(*args, **options)
  File "/Users/seawolf/repos/django-autometrics/.eggs/Django-1.8.18-py2.7.egg/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/seawolf/repos/django-autometrics/.eggs/Django-1.8.18-py2.7.egg/django/core/management/commands/test.py", line 90, in handle
    failures = test_runner.run_tests(test_labels)
  File "/Users/seawolf/repos/django-autometrics/.eggs/Django-1.8.18-py2.7.egg/django/test/runner.py", line 211, in run_tests
    result = self.run_suite(suite)
  File "/Users/seawolf/repos/django-autometrics/.eggs/Django-1.8.18-py2.7.egg/django/test/runner.py", line 178, in run_suite
    ).run(suite)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/runner.py", line 151, in run
    test(result)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/Users/seawolf/repos/django-autometrics/.eggs/djangae-0.9.9-py2.7.egg/djangae/test_runner.py", line 125, in _wrapped
    bed = init_testbed()
  File "/Users/seawolf/repos/django-autometrics/.eggs/djangae-0.9.9-py2.7.egg/djangae/test_runner.py", line 115, in init_testbed
    getattr(bed, init_name)(**stub_kwargs.get(init_name, {}))
  File "/Users/seawolf/dev/google-cloud-sdk/platform/google_appengine/google/appengine/ext/testbed/__init__.py", line 585, in init_images_stub
    raise StubNotSupportedError(msg)
google.appengine.ext.testbed.StubNotSupportedError: Could not initialize images API; you are likely missing the Python "PIL" module.
('Command failed with exit code', 1)
```

The only way I can find to eliminate the error is to manually install `Pillow`. It seems to me that if this is a real dependency then the `djangae` package itself should explicitly include this dependency.

**Comment by seawolf42** [comment]
The package in question is https://github.com/seawolf42/django-autometrics. I am currently trying to get it working with Google SDK versions greater than 137.0.0 and discovered this issue.

**Comment by davidwtbuxton** [comment]
The Djangae test runner changed recently, and now it sets up a full SDK testbed, including the images API.

You can set a different test runner with [the `TEST_RUNNER` setting][test_runner], but may need to create your own base `unittest.TestCase` class which initialises the testbed and only the services your application wants to test.

The [SDK docs show how to setup the testbed][testbed].

Regarding whether Pillow / PIL should be a declared dependency, I would prefer that Djangae does **not** specify Pillow / PIL. For App Engine projects you will be installing Djangae outside the regular site-packages anyway (in order to deploy it) and if Pillow was installed alongside it you would then need to make sure Pillow was excluded from the deployment (else you get errors on App Engine). Also it isn't a direct dependency of Djangae, but of Django / App Engine. Django is a good example of a project which requires Pillow / PIL for a lot of its functionality, but which doesn't specify it as a requirement in its `setup.py`.

[testbed]: https://cloud.google.com/appengine/docs/standard/python/tools/localunittesting
[test_runner]: https://docs.djangoproject.com/en/1.10/ref/settings/#test-runner

**Comment by Kazade** [comment]
I think we can probably conditionally initialize the Images stub if PIL is available (perhaps with a warning if it's not). That's probably better than just dying outright or forcing a PIL requirement for testing.

**Comment by seawolf42** [comment]
I second that... the idea is to handle things gracefully if the library is not present rather than a hard exit. Perhaps a warning in the logs (similar to the warnings about deprecating functionality)?

---------- 
jeffrey k eliasen - technologist, philosopher, agent of change
blog <http://jeff.jke.net/> | linkedin <http://www.linkedin.com/pub/jeffrey-eliasen/3/a83/b76> | google+ <http://plus.google.com/+JeffreyEliasen> | facebook <http://facebook.com/jeffrey.eliasen> | twitter <http://twitter.com/jeffreyeliasen>
