### ISSUE TITLE
Djangae's default configuration requires mapreduce / pipeline packages

### ISSUE THREAD

**Issue by davidwtbuxton** [potatolondon/djangae#926]
Hi,

A default configuration of Djangae with a Django project requires the installation of the mapreduce / pipeline packages, whether or not `djangae.contrib.processing.mapreduce` is included in the `INSTALLED_APPS` setting.

This is annoying. This was raised somewhere in another ticket, but I can't find it now.

The cause is most Django projects will have something like the following in the root urlconf module:

```
urlpatterns = (
    url(r'^_ah/', include('djangae.urls')),
)
```

Recent versions of Djangae have `import djangae.contrib.processing.mapreduce.urls` at the module level of `djangae/urls.py`, which means Python imports `djangae/contrib/processing/mapreduce/__init__.py`, which imports `djangae/contrib/processing/mapreduce/helpers.py`, which imports all the mapreduce and pipeline stuff. 

This was tested using Djangae revision d3067f0e1cc371690ae9fb9f715e322ed4b056db (current HEAD of master) and Django 1.8.18.

Importing the `djangae/urls.py` module should not trigger an import of the mapreduce stuff unless it is necessary.

David B.

**Comment by davidwtbuxton** [comment]
I can run `python manage.py runserver` and the server starts, but the first request gives me this traceback:

```
ERROR    2017-06-01 23:10:03,851 base.py:256] Internal Server Error: /
Traceback (most recent call last):
  File "/Users/jeff/example/sitepackages/django/core/handlers/base.py", line 223, in get_response
    response = middleware_method(request, response)
  File "/Users/jeff/example/sitepackages/debug_toolbar/middleware.py", line 129, in process_response
    panel.generate_stats(request, response)
  File "/Users/jeff/example/sitepackages/debug_toolbar/panels/request.py", line 45, in generate_stats
    match = resolve(request.path)
  File "/Users/jeff/example/sitepackages/django/core/urlresolvers.py", line 521, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/Users/jeff/example/sitepackages/django/core/urlresolvers.py", line 365, in resolve
    for pattern in self.url_patterns:
  File "/Users/jeff/example/sitepackages/django/core/urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/jeff/example/sitepackages/django/core/urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/jeff/example/example/urls.py", line 34, in <module>
    url(r'^_ah/', include('djangae.urls')),
  File "/Users/jeff/example/sitepackages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/jeff/example/sitepackages/djangae/urls.py", line 4, in <module>
    import djangae.contrib.processing.mapreduce.urls
  File "/Users/jeff/example/sitepackages/djangae/contrib/processing/mapreduce/__init__.py", line 4, in <module>
    from .helpers import *
  File "/Users/jeff/example/sitepackages/djangae/contrib/processing/mapreduce/helpers.py", line 2, in <module>
    import pipeline
ImportError: No module named pipeline
```
