### ISSUE TITLE
Reverse relationships do not work for RelatedSetFields.

### ISSUE THREAD

**Issue by kdiale-nerdery** [potatolondon/djangae#961]
For a quick example, create a group and then add a user to that group with the following snippet.

`group.gaedatastoreuser_set.add(user)`

This will throw this error:

`AttributeError: 'Group' object has no attribute 'groups_ids'`

It appears that the reverse relationship is not identifying itself correctly and django spazzes out. If you'll see it's being misidentified:

```
>>> group.gaedatastoreuser_set.field.attname
'groups_ids'
```

I'm unsure of a workaround at this time.

**Comment by moggers87** [comment]
This should work instead:

```
user.groups.add(group)
user.save()
```

Here's a complete traceback:

```
>>> group.gaedatastoreuser_set.add(user)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/moggers/workspace/subscribae/sitepackages/prod/djangae/fields/related.py", line 142, in add
    field_value = self.field.value_from_object(self.instance)
  File "/home/moggers/workspace/subscribae/sitepackages/prod/django/db/models/fields/__init__.py", line 909, in value_from_object
    return getattr(obj, self.attname)
AttributeError: 'Group' object has no attribute 'groups_ids'
```

**Comment by adamalton** [comment]
I'm not entirely convinced that we should support adding objects to a related set field via the reverse relation, because it creates a very counter-intuitive flow in which you have to save the object which you added, rather than the one which was added to.  E.g.:

```python
# This will NOT save the relation
group.gaedatastoreuser_set.add(user)
group.save() 

# Because you actually need to do this:
group.gaedatastoreuser_set.add(user)
user.save()
```

I think it would probably be better to raise an error with a helpful message, rather than allow the `.add()` to work but then require the opposite object to be saved.
