### ISSUE TITLE
Remote shell not work when using latest Google Cloud SDK

### ISSUE THREAD

**Issue by seawolf42** [potatolondon/djangae#973]
When trying to run `python manage.py --remote=sandbox shell` I get the following error:

```bash
$ python manage.py --remote=sandbox shell
Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/seawolf/repos/myproject/site/sitepackages/djangae/core/management/__init__.py", line 62, in execute_from_command_line
    return _execute_from_command_line(namespace.sandbox, ['manage.py'] + other_args, **overrides)
  File "/Users/seawolf/repos/myproject/site/sitepackages/djangae/core/management/__init__.py", line 42, in _execute_from_command_line
    **sandbox_overrides
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/seawolf/repos/myproject/site/sitepackages/djangae/sandbox.py", line 485, in activate
    import google.appengine.tools.devappserver2.python.sandbox as sandbox
ImportError: No module named sandbox
```

This is using the latest SDK, not sure which version stopped working:

```bash
$ gcloud -v
Google Cloud SDK 173.0.0
alpha 2017.09.15
app-engine-python 1.9.60
beta 2017.09.15
bq 2.0.26
core 2017.09.25
gcloud 
gsutil 4.27
kubectl 
```

**Comment by seawolf42** [comment]
Note that this also breaks everything that depends on the remote shell, such as migrations.

**Comment by moggers87** [comment]
Pretty sure this is a duplicate of #964

**Comment by seawolf42** [comment]
Very well could be, that issue doesn't make the symptoms clear but it sounds about right. I'll keep this open for now and revisit once that one is closed if that's OK.

**Comment by davidwtbuxton** [comment]
Related #1035
