### ISSUE TITLE
how we can use https://cloud.google.com/storage/docs/reference/libraries#client-libraries-install-python?

### ISSUE THREAD

**Issue by vinaymavi** [potatolondon/djangae#978]
How we can use client library https://cloud.google.com/storage/docs/reference/libraries#client-libraries-install-python with **djangae**?

**Comment by davidwtbuxton** [comment]
Hi,

Can you provide more details on the problem please?

For general questions about using Djangae (as opposed to bug reports) there is a mailing list: https://groups.google.com/forum/#!forum/djangae-users

David B

**Comment by vinaymavi** [comment]
I need to read, write and update google cloud storage bucket as per [documentation](https://cloud.google.com/storage/docs/reference/libraries#client-libraries-install-python),

This documentation suggest the python package **google-cloud-storage** to access storage when i tried with with given code.
```
from google.cloud import storage

storage_client = storage.Client()
bucket_name = 'letstypeorg.appspot.com'


class Bucket:
    def __init__(self):
        self.bucket = storage_client.get_bucket(bucket_name=bucket_name)

    def get_list(self):
        dir_list = []
        iterator = self.bucket.list_blobs()
        for blob in iterator:
            dir_list.append(blob.blob_name)
        return dir_list

```
I am getting server error 
```
(/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/runtime/wsgi.py:279)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 267, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/base/data/home/apps/s~letstypeorg/20171009t000951.404663238717411655/sitepackages/prod/djangae/wsgi.py", line 67, in __call__
    return self.wrapped_app(environ, start_response)
  File "/base/data/home/apps/s~letstypeorg/20171009t000951.404663238717411655/sitepackages/prod/django/core/handlers/wsgi.py", line 177, in __call__
    response = self.get_response(request)
  File "/base/data/home/apps/s~letstypeorg/20171009t000951.404663238717411655/sitepackages/prod/django/core/handlers/base.py", line 230, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/base/data/home/apps/s~letstypeorg/20171009t000951.404663238717411655/sitepackages/prod/django/core/handlers/base.py", line 292, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/base/data/home/apps/s~letstypeorg/20171009t000951.404663238717411655/sitepackages/prod/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/base/data/home/apps/s~letstypeorg/20171009t000951.404663238717411655/sitepackages/prod/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/base/data/home/runtimes/python27_experiment/python27_dist/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/base/data/home/apps/s~letstypeorg/20171009t000951.404663238717411655/letstypeorg/urls.py", line 5, in <module>
    from webapp import views
  File "/base/data/home/apps/s~letstypeorg/20171009t000951.404663238717411655/letstypeorg/webapp/views.py", line 4, in <module>
    from google_cloud_storage import Bucket
  File "/base/data/home/apps/s~letstypeorg/20171009t000951.404663238717411655/letstypeorg/webapp/google_cloud_storage.py", line 2, in <module>
    from google.cloud import storage
ImportError: No module named cloud
```

**Comment by davidwtbuxton** [comment]
Have you definitely included the google.cloud package with your deployed application? Does it work in the local dev_appserver.py?

Alternatively use the cloudstorage package, which doesn't mess with namespaces (and which has a much nicer API in my opinion).

https://pypi.python.org/pypi/GoogleAppEngineCloudStorageClient

https://cloud.google.com/appengine/docs/standard/python/googlecloudstorageclient/read-write-to-cloud-storage

Closing this issue because it is not a Djangae bug. Please use the mailing list.
